### ISSUE TITLE
Generate pure typings in different file

### ISSUE THREAD

**Issue by kfrancis** [reinforced/Reinforced.Typings#10]
Hey,

One question - I'd like to generate the enum declaration in non-definition files (just .ts) while all the interfaces go into .d.ts files. Is that possible?

**Comment by pavel-b-novikov** [comment]
Yes. 
* Enable RtDivideTypesAmongFiles in settings.xml
* Use [TsFile] attribute or .ExportAs*() .ExportTo fluent call
