### ISSUE TITLE
Empty lines between properties of interface/class

### ISSUE THREAD

**Issue by ReinisV** [reinforced/Reinforced.Typings#103]
When code is generated, there are no empty lines between properties on an interface. If `GenerateDocumentation()` is turned on, it quickly gets quite claustrophobic and not as easy to distinguish between where information for one field ends and another one starts.

```
export interface SomeInterface
{
	/**
	* text text text.
	* Text
	*/
	SomeField: number;
	/**
	* text text text.
	* Text
	* text text text.
	*/
	SomeOtherField: number;
	/**
	* text text text.
	* Text
	*/
	AnotherField: string;
	/**
	* text text text.
	* Text
	*/
	SomeFieldAgain: Date;
}
```

I wanted to add empty lines between properties on an interface by adding `RtRaw(Environment.NewLine)` before `RtField` entries in `RtInterface.Members`, but could not, because there is no `Order` field for `RtRaw` and all of the newlines just get plunked at the [beginning of the interface](https://github.com/reinforced/Reinforced.Typings/blob/d11a460f79ca646ca20ee7ee03c3ff52b5c39d06/Reinforced.Typings/Visitors/TypeScript/TypeScriptExportVisitor.RtInterface.cs#L30)

**Feature request**: an Order property for `RtRaw` could be added, so that random text can be inserted wherever it is necessary. Random text only at the beginning of an interface/class is only useful in a limited number of cases.

**Comment by PandaWood** [comment]
I wonder if this issues ties into the the problem of output generated being CLR dependent - that I discovered while running tests in Mono... ?

That is, **TokenizingComparerTests** fail on Mono because the tests expect the lines in a certain exact order where Mono produces the exact same TypeScript classes but with the lines in a different order.

**Comment by pavel-b-novikov** [comment]
TokenizingComparerTests fail on mono because seems that there is indeed different members order there. I have fixed these tests by adding ```.ReorderMembers``` in v. 1.5 to all tests and, therefore, fixing members appearing order. 

Regarding main issue: I will try to think something out

**Comment by pavel-b-novikov** [comment]
[In version 1.5 you will have `LineAfter`](https://github.com/reinforced/Reinforced.Typings/blob/features-1.5/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.LineAfterTest.cs)

**Comment by ReinisV** [comment]
Awesome, thank you for that. Will be waiting for the release then. 

Is there a time frame planned for the release? Like two weeks or a month? Or specific items that need to be completed before the release? Just so that I know when to expect the updates to drop to NuGet.
