### ISSUE TITLE
Error if Reinforced.Typings.settings.xml doesn't exist in project (v.1.4.96)

### ISSUE THREAD

**Issue by GreenAirplane** [reinforced/Reinforced.Typings#104]
There is a breaking change in v.1.4.96 which triggers errors during build process if there is no Reinforced.Typings.settings.xml file in a project.

Use case:
- WebApp project has Reinforced.Typings.settings.xml file and all the configuration.
- Models project has classes decorated with attributes (e.g. TsClass).

Expected behavior (same like it was in previous versions):
Solution builds without errors, WebApp project has TypeScript file with classes from Models project.

Current behavior:
2 erros triggered:

1. Project "(removed)\Reinforced.Typings.settings.xml" was not imported by "(removed)\.nuget\packages\reinforced.typings\1.4.96\build\Reinforced.Typings.targets" at (22,5), due to the file not existing.

2. MSB4019 The imported project "(removed)\Reinforced.Typings.settings.xml" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	ClassLibrary1	(removed)\.nuget\packages\reinforced.typings\1.4.96\build\Reinforced.Typings.targets	22

Possible solution:
Revert changes in Reinforced.Typings\stuff\Reinforced.Typings.targets:

from `<Import Project="$(RtSettingsXml)" />`
to `<Import Project="$(RtSettingsXml)" Condition="Exists($(RtSettingsXml))" />`

**Comment by pavel-b-novikov** [comment]
Can you do one small thing for me? Can you place this condition back locally and check if Visual Studio will catch your changes in settings.xml? 

This change was made in order to fix #92, but I'm not sure if it is correct because both options do work on my machine.

**Comment by GreenAirplane** [comment]
Just checked and condition fixes the issue. 

I do understand the reason for this change based on #92. At the same time, I can't say that e.g. in my team we change the config often. To be honest, I don't think that anyone changed it since I've added it. However, I don't like that I have multiple config files and some of them are basically empty files just to prevent errors on build. It can be misleading and it breaks existing projects..

**Comment by GreenAirplane** [comment]
By the way, based on the documentation, Choose block may work for #92 as well. I will test it and post results

**Comment by pavel-b-novikov** [comment]
> Choose block may work

No, it cannot. I've just checked - imports are not possible within `Choose` blocks. 
And actually I cannot reproduce issue #92 in my VS. After changing settings.xml and rebuild - changes are taking place as should. Moreover, it works on all my colleagues' machines. Can you also try? If it works for you also - then it really makes sense to revert that change.

**Comment by GreenAirplane** [comment]
So, you are right, `Choose` doesn't work and I actually able to reproduce the issue from #92.

But I found another workaround! If you will check the MSBuild docs then you may notice that there is a "hack". You can use condition on ImportGroup and it would be reevaluated.

So, I've changed the targets file to the following:

` <ImportGroup Condition="Exists($(RtSettingsXml))">
    <Import Project="$(RtSettingsXml)" />
  </ImportGroup>`

Works like magic for me. Please note that you have to use "Rebuild Solution" command if there were no changes in code to trigger the proper build process.

The way I've tested:
1. Opened test project which doesn't have settings.xml file.
2. Built it and no ".ts" file generated.
3. Added settings.xml file
4. Used "Rebuild Solution" command.

Result: a new ts file generated according to my config.

Another test:
1. Opened a test project with settings.xml.
2. Built it and models.ts file generated.
3. Changed RtTargetFile to models2.ts
4. Used "Rebuild Solution" command.

Result: models2.ts file generated.

So, looks like ImportGroup workaround works..

**Comment by pavel-b-novikov** [comment]
Indeed. Just have made and published .97 version with your workaround. 
Thanks a lot. Wait for NuGet reindex and have fun.
