### ISSUE TITLE
Build Error with .Net core 2.1 and RT 1.4.97

### ISSUE THREAD

**Issue by chriskooken** [reinforced/Reinforced.Typings#105]
This is a follow on to [Issue 102](https://github.com/reinforced/Reinforced.Typings/issues/102)

After updating to 1.4.97, I get this error when I try to build on .Net Core 2.1.

> The "Reinforced.Typings.Integrate.RtCli" task could not be loaded from the assembly C:\Users\chris.nuget\packages\reinforced.typings\1.4.97\build\net45\Reinforced.Typings.Integrate.dll. Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Another user reported a similar issue but a little different:

> C:\Users\pd\.nuget\packages\reinforced.typings\1.4.97\build\Reinforced.Typings.targets(59,3): error MSB4062: The "Reinforced.Typings.Integrate.RtCli" task could not be loaded from the assembly C:\Users\pd\.nuget\packages\reinforced.typings\1.4.97\build\netstandard1.6\Reinforced.Typings.Integrate.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [MyProject.Web.csproj]

**Comment by pavel-b-novikov** [comment]
Give me couple of hours

**Comment by pavel-b-novikov** [comment]
1.5 published. Wait for nuget reindex and notify me about errors. Something critical I can fix immediately

**Comment by chriskooken** [comment]
@pavel-b-novikov I can confirm, everything is working for me now. Thanks so much for your help on this. I truly believe this is the best approach out there for generating TS models. Thanks for all the hard work!

**Comment by GreenAirplane** [comment]
@pavel-b-novikov and it works for me as well! Thanks for the quick fix!
