### ISSUE TITLE
Option to configure line endings

### ISSUE THREAD

**Issue by romansp** [reinforced/Reinforced.Typings#107]
After @PandaWood effort to improve cross-platform support, it would be awesome to have an option to enforce what combination (LF vs CRLF) to use for line endings during TypeScript generation.

Let me know if you're interested in such PR.

**Comment by PandaWood** [comment]
I think you should do it

**Comment by pavel-b-novikov** [comment]
We already have `LineAfter` made in #103 . You can start from there.

**Comment by romansp** [comment]
Yeah, because counts for CRLF/LF differences it's the exact reason I want to specify it explicitly. Our uses both both MacOS and Windows machines to develop and I'm trying to avoid irrelevant line ending changes. Hope that makes my intent clear.

**Comment by pavel-b-novikov** [comment]
Excuse me, but... well, I think you'd better not to commit generated files to your repo. It it better for consistency and can help to avoid "old version" problems

**Comment by romansp** [comment]
Can't agree more with you. Reason why we committed generated files is because Reinforced.Typings couldn't generate them in our linux-based CI env (now it can, and we're going to reevaluate this decision). Yes, we're not committing .js generated by `tsc`.
