### ISSUE TITLE
Does not work with .net core 2.2

### ISSUE THREAD

**Issue by luisvsilva** [reinforced/Reinforced.Typings#109]
When I add the nuget , project stops compiling with: 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NETSDK1005	Assets file 'project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.2'. Ensure that restore has run and that you have included 'netcoreapp2.2' in the TargetFrameworks for your project.

Removing the nuget, project compiles normally.

**Comment by pavel-b-novikov** [comment]
Please describe your project and environment

**Comment by luisvsilva** [comment]
OK found out what the issue was, 

in the configuration file:

Reinforced.Typings.settings.xml

I had:

`<TargetFramework>netcoreapp2.1</TargetFramework>`

Although my project was set to target 2.2. 

Is this directive necessary?, if I comment it out it seem to run without issues.

**Comment by pavel-b-novikov** [comment]
This is not necessary and was workaround for previous version

**Comment by pavel-b-novikov** [comment]
Well, you can safely remove it now and use [`RtForceTargetFramework`](https://github.com/reinforced/Reinforced.Typings/wiki/Reinforced.Typings.settings.xml#RtForceTargetFramework) instead

**Comment by luisvsilva** [comment]
Thanks!!!!
