### ISSUE TITLE
ShouldBePascalCase

### ISSUE THREAD

**Issue by kfrancis** [reinforced/Reinforced.Typings#11]
There are times when the interface generated needs to specifically use pascal case (MVC SelectListItem), but we much like setting `RtCamelCaseForProperties` true. We could do it by setting `RtCamelCaseForProperties` false and then adding the `[TsProperty(ShouldBeCamelCased: true)]` on every property but that is pretty messy.

What I'd love is if there would be the opposite, that we could just use `[TsProperty(ShouldBePascalCased: true)]` on the properties that need it for compatibility with MVC.

**Comment by kfrancis** [comment]
Also, another possible option would be a property to keep the casing intact, `[TsProperty(KeepCasingIntact:true)]`

**Comment by pavel-b-novikov** [comment]
Accepted. Will be changed in next version

2016-04-15 0:45 GMT+06:00 Kori Francis <notifications@github.com>:

> Also, another possible option would be a property to keep the casing
> intact, [TsProperty(KeepCasingIntact:true)]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/reinforced/Reinforced.Typings/issues/11#issuecomment-210094739>
>



-- 
Sincerely yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447
