### ISSUE TITLE
Consider making RtSettingsXml optional

### ISSUE THREAD

**Issue by takerukoushirou** [reinforced/Reinforced.Typings#112]
I integrated Reinforced Typings nicely into the build process which does not use any `Reinforced.Typings.settings.xml` file (instead, the corresponding properties are constructed in my own MSBuild imports).
Everything worked perfectly until I upgraded from 1.4.95 to 1.5.1 and type generation stopped. Looking at the MSBuild targets, this is caused due to the new `Condition="Exists($(RtSettingsXml))"` on the `PropertyGroup` that updates `TargetsTriggeredByCompilation`. Is this condition necessary? It seems obsolete to me, as the `RtSettingsXml` import also depends on the file existence. Currently I need to keep empty `Reinforced.Typings.settings.xml` files in every project for which types are generated.

Looking at other issues, I guess #80 was the cause for this condition. If switching from the file existence condition to e.g. settings properties-based conditions is not easily possible, an alternative might be to allow users to define `RtSettingsXml` instead of always assigning a hard-coded path (by simply adding the condition whether the value is still empty).

**Comment by pavel-b-novikov** [comment]
Might be already discussed in #104
