### ISSUE TITLE
export class without module using FluentApi

### ISSUE THREAD

**Issue by LCvijovic09** [reinforced/Reinforced.Typings#113]
Hey, 
this might not be an issue, but I just can`t figure it out. 
Can someone please explain to me how to export a class without it being a module? 
Thanks.

I am trying to export a class for Angular 6, not sure if it is relevant, using C#.
Code:
`builder.ExportAsClasses(exportTypes.Reverse().Skip(1).Reverse(), (_) =>
            {
                _.AddImport("{ Injectable }", "@angular/core")
                    .AddImport("{ HttpClient, HttpHeaders, HttpParams }", "@angular/common/http")
                    .AddImport("{ Observable }", "rxjs")
                    .AddImport("{ map }", "rxjs/operators")
                    .AddImport("{ Settings }", "@app/common/settings")
                    .ExportTo(_.Type.Name + ".ts").WithCodeGenerator<AngularControllerGenerator>();
            });`

P.S. sorry for the code aligning, I don`t know how to format it :)

**Comment by halfee** [comment]
Hi, you need UseModules. Look [here](https://github.com/reinforced/Reinforced.Typings/wiki/Configuration-attributes#TsGlobal)

```C#
builder.Global(conf => conf.UseModules());
```

**Comment by LCvijovic09** [comment]
Hey, thanks for the reply, I will give it a try today, hopefully and will
let you know.
And sorry for the late reply. :)

**Comment by LCvijovic09** [comment]
Perfect. Thanks halfee. It now works perfectly.
