### ISSUE TITLE
tslint: Import sources within a group must be alphabetized. (ordered-imports)

### ISSUE THREAD

**Issue by devel0** [reinforced/Reinforced.Typings#117]
imports should sorted

## current behavior

```js
import { IUser } from './IUser';
import { IJobItem } from './IJobItem';
import { IJobDoc } from './IJobDoc';
```

## expected behavior

```js
import { IJobDoc } from './IJobDoc';
import { IJobItem } from './IJobItem';
import { IUser } from './IUser';
```

## workaround

configure `tslint.json` to exclude generated files

**Comment by pavel-b-novikov** [comment]
You can use [reference processor](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.ReferencesProcessor.cs) and sort imports/references however you want.
