### ISSUE TITLE
Setting properties on config attributes by default.

### ISSUE THREAD

**Issue by justinmwarner** [reinforced/Reinforced.Typings#118]
<sub>
First, thanks so much for making this library. The team I work on have been using it with little issues for months and it has been a changer in the workplace.
</sub>
<sub>
Second, apologies if this is not the right form to use to raise questions. Let me know and I can create them elsewhere.
</sub>

We use the property, `AutoExportMethods` on the `TsInterface`. But we have to remember to add this to every TsInterface.  I was wondering if we have a way of setting this to true by default in the config for Reinforced Typings?

Thanks again,
Justin W.

**Comment by justinmwarner** [comment]
Just saw in the README the correct place. Closing.

**Comment by MathiasCiarlo** [comment]
For anyone wondering how to do this. I wanted to make `[TsInterface(IncludeNamespace = false, AutoExportMethods = false)]` default so all I have to do is this: `[TsInterface]`. I could not find a way to configure this, but I solved it by extending the TsInterface attribute like this:
```cs
using Reinforced.Typings.Attributes;

namespace MyApp.Infrastructure
{
    public class ExtendedTsInterfaceAttribute : TsInterfaceAttribute
    {
        public ExtendedTsInterfaceAttribute()
        {
            IncludeNamespace = false;
            AutoExportMethods = false;
        }
    }
}
````
Now I can use it in my classes like this:
```cs
[ExtendedTsInterface]
public class SampleClass
{
   // Stuff
}
```
