### ISSUE TITLE
.net core 3.0 preview

### ISSUE THREAD

**Issue by nightBaker** [reinforced/Reinforced.Typings#124]
Can't build project for .net core 3.0 

/root/.nuget/packages/reinforced.typings/1.5.2/build/Reinforced.Typings.targets(59,3): error MSB6006: "" exited with code 150.

**Comment by pavel-b-novikov** [comment]
RT will be updated to .net core 3.0 when final version of one will be released (not CTP)

**Comment by jensdc92** [comment]
I'm using version 1.5.3 and I'm on .net core 3 preview 5. Adding this in xml solved my issue:

    <RtForceTargetFramework>netcoreapp2.1</RtForceTargetFramework>

**Comment by versovsky** [comment]
@jensdc92  Have u had problems with 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	RT0999	Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

	?

**Comment by jensdc92** [comment]
> @jensdc92 Have u had problems with
> 
> > Severity	Code	Description	Project	File	Line	Suppression State
> > Error	RT0999	Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
> 
> ```
> ?	
> ```

After upgrading to .net core 3 RC1 I do. Did you find a solution for this?

**Comment by pavel-b-novikov** [comment]
Main discussion is [here](https://github.com/reinforced/Reinforced.Typings/issues/137)

**Comment by ranjeetahangal** [comment]
I faced this issue when downloaded the corresponding sdk as per my project requirement but with wrong bit specification.  (X86, X64) choose as per your system. After installing with proper bit specification it worked.
