### ISSUE TITLE
Camel Case Inconsistent With Json.NET

### ISSUE THREAD

**Issue by poita66** [reinforced/Reinforced.Typings#126]
When using `CamelCaseForProperties()` in Reinforced.Typings, the produced names are different from what the Json.NET `CamelCasePropertyNamesContractResolver` produces.

Example C# property name:
`ExternalID`

From Json.NET:
`externalID`

From Reinforced.Typings:
`externalId`

As I assume that most people using your software would be using it with Json.NET, an easy configuration option to specify that it should use the same logic for camel case would be ideal.

**Comment by pavel-b-novikov** [comment]
Sorry, 0-dependency is my principle. If you would like to - RT has thousand of ways to simulate behaviour that you've just described.

**Comment by poita66** [comment]
What I imagined wouldn't be a dependency per-se, but a compatibility option.
Would it be worth me making a PR to explain what I'm thinking? If not, maybe a wiki entry on how to get the RT to simulate the desired behavior?

**Comment by pavel-b-novikov** [comment]
Sure! Both options affordable

**Comment by poita66** [comment]
So I just realized (while analyzing the code to make a PR) that the logic is in-fact consistent and that I shouldn't log issues just before going to bed.

Thanks for your help and apologies for wasting your time!
