### ISSUE TITLE
Multiline string

### ISSUE THREAD

**Issue by nvirth** [reinforced/Reinforced.Typings#127]
Multiline C# strings end up in incorrect TypeScript code.

This:

		public static MyClass
		{
			public static string MyStaticProperty = @"My
	multiline
	string";
		}

Will result in smg similar to this:

	  export abstract class MyClass
	  {
	    public static MyStaticProperty: string = 'My
	multiline
	string';
	  }

Please exchange ' with `, so multiline default values will result in correct TypeScript code.

Thank you!

**Comment by pavel-b-novikov** [comment]
My fault. Use ```\n``` as temporary workaround

**Comment by pavel-b-novikov** [comment]
Fixed in version 1.5.4 ([test](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.NvirthMultilineString.cs))
