### ISSUE TITLE
ReinforcedTypingsGenerate runs after CompileTypeScriptWithTSConfig

### ISSUE THREAD

**Issue by nvirth** [reinforced/Reinforced.Typings#128]
TSC build step runs before Reinforced.Typings generation build step by me.
Is this correct this way?
Seems invalid for me.
My plan was not to commit the generated ts files, I thought they will be already regenerated before TSC runs.
Is there an option to do so?

**Comment by nvirth** [comment]
Adding this seems to wokr for me:

    <PropertyGroup>
      <CompileTypeScriptDependsOn>
        CompileTypeScriptWithTSConfig;
        $(CompileTypeScriptDependsOn);
      </CompileTypeScriptDependsOn>
    </PropertyGroup>

I'm wondering why this isn't there by default, or why nobody complained about this yet.
Will this ruin smg else maybe?

Thank you very much!

**Comment by pavel-b-novikov** [comment]
There is option in ```Reinfroced.Typings.settings.xml``` to disable RT call as well as TypeScript config. 
Problem is that msbuild compiles TypeScript before building C# code. So if it would be vise versa - then there might be no problems. As result, I've had to make some dirty msbuild hacks to change this behaior. See details [here](https://github.com/reinforced/Reinforced.Typings/blob/master/stuff/Reinforced.Typings.targets)

**Comment by nvirth** [comment]
I see the issue.

What do you think of an option in the xml config to move the TSC task from "BeforeBuild" to "AfterBuild"?
Could be false by default.

If enabled, the build order would be `C# build` -> `RT build` -> `TS build`
That way, it would be possible to ignore the generated files from source control.

**Comment by pavel-b-novikov** [comment]
Look. If you want to ignore generated files in source control - it can be done without modifying RT

**Comment by nvirth** [comment]
How?
The current build order is `TS build` -> `C# build` -> `RT build`.
So the RT generated typescript files won't be generated yet at the `TS build` step, thus the TSC will fail, if any of my typescript files use anything from the generated files - which is, of course, the goal of the generation.
It is a chicken egg issue, TS compile fails, because it would need files RT compile would provide, but RT compile will never run because TS compile fails.

**Comment by pavel-b-novikov** [comment]
Most of people who use RT either:
1) Include generated files into source control ([like here](https://github.com/reinforced/Reinforced.Typings/issues/107) )
2) Separate their client-side projects from C# ones and use ```tsc``` explicitly along with other JS build systems (many people) 
3) Playing around with disabling RT/TS compilation
4) Generate their typings into 2-3 files that are not difficult to include to repo

Such variety of solutions.
