### ISSUE TITLE
List<Tuple<int,bool>> generates to wrong type

### ISSUE THREAD

**Issue by stevenfowler16** [reinforced/Reinforced.Typings#129]
`List<Tuple<int,bool>>` generates to type `[number,boolean][]` 

In C# to serialize back into a tuple the type needs to be `{item1:number,item2:boolean}[]`

**Comment by pavel-b-novikov** [comment]
Use [substitutions](https://github.com/reinforced/Reinforced.Typings/wiki/Types-Resolution#substitutions) to avoid this behavior

**Comment by stevenfowler16** [comment]
I'm not sure if closing the issue is correct. The System.Tuple and
Typescript Tuple are not synonymous.
