### ISSUE TITLE
Version for MVC 6.0

### ISSUE THREAD

**Issue by MV10** [reinforced/Reinforced.Typings#13]
I have a very large, very complex multi-solution system spanning both .NET 3.5 and .NET Core 1.0 compilations for my POCO. Now we're doing some Angular stuff for database maintenance chores and need to share out the POCOs as TS files, so I built a skeleton non-core .NET console project, added Reinforced.Typings, then referenced my DLL in the configuration as follows:

&lt;ItemGroup&gt;
&lt;RtAdditionalAssembly Include="$(SolutionDir)\..\..\ClientLibraries\DataDef\bin\Debug\net35\DataDef.dll" /&gt;
&lt;/ItemGroup&gt;

The problem is that VS says RtAdditionalAssembly is not a valid child of ItemGroup. This is VS2015 Update 3 with all patches as of Aug 2016.

**Comment by pavel-b-novikov** [comment]
I presume that this error is related to VS2015 project format (.xproj). Previous version of MSBuild's syntax (according to MSBuild docs) is 
```xml
<ItemGroup Condition="'String A' == 'String B'">
    <Item1>... </Item1>
    <Item2>... </Item2>
</ItemGroup>
```

So it have to consume any children of an ItemGroup. So therefore I presume that problem is not in RT itself, but in Visual Studio and MSBuild. 

Could you contact me directly, because you are doing very interesting option of RT integration? Skype: nsu_the_cjay.

**Comment by MV10** [comment]
I don't use Skype, sorry. I didn't consider that my multi-targeted DLL doesn't contain any RT attributes (since the DLL targets both .NET35 and Core 1.0, I can't easily add RT to the project) so I can't really use the Assembly approach even if this XML warning hadn't come up.

I was able to do the static class configuration and get the desired output.

However I'm willing to help if you need anything else relating to this project configuration. I'd also be happy to test any Core changes you might make, I'd prefer to use the attribute approach and output my TS files from the same project that produces the data definition DLL.

**Comment by pavel-b-novikov** [comment]
Well, the problem is that it is not so easy to make .NETCore version of RT. Mainly because the main feature of RT is integration within project building process. I still couldnt find extension point for embedding RT calls to .xproj build script. If you have information about how to do that - please tell me :) Will appreciate any help.

**Comment by MV10** [comment]
I would think you need the "tools" and "scripts" section of the project.json file. 

[https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json)

I hate to say it, but MS has announced that project.json is going away in the next VStudio, they're going back to MSBUILD for everything, so unfortunately this would be a short-lived fix. (VS2015 is version 14, they're dropping year-names, so the next one will, confusingly, be called VS15). I think JSON files are terrible for configuration, but that decision has stalled a lot of VS14 development/integration.

**Comment by pavel-b-novikov** [comment]
Am I right that you suggest just sit still and wait? :)

**Comment by MV10** [comment]
Well, it _might_ be an easy fix. 

You almost certainly will have to make other changes to support Core though. Part of my project uses reflection very heavily but it only took me a few minutes to fix that. I didn't see much else in RT that looked like it would be impacted.

If it really is as simple as fixing reflection (same features are available, they just revised the API a little) and adding RT to the project.json, it may be worth updating it anyway. I know I'd appreciate it!  :)

**Comment by pavel-b-novikov** [comment]
btw, I've just found year-old announce that project.json will not be supported in the future.
https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

So all the msbuild hacks made in RT will stay valid

**Comment by pavel-b-novikov** [comment]
Case closed
https://github.com/reinforced/Reinforced.Typings/issues/48
