### ISSUE TITLE
Error after upgrade to v1.5.3 with .net core 2.2, 

### ISSUE THREAD

**Issue by skalma** [reinforced/Reinforced.Typings#130]
Hi Pavel, 
I get error the following error when building my project against .netcoreapp2.2 after upgrade to 1.5.3: 

MSB6006	"" exited with code -2147450730.	C:\Users\skalma\.nuget\packages\reinforced.typings\1.5.3\build\Reinforced.Typings.targets	Line 59

I have set <RtForceTargetFramework>netcoreapp2.2</RtForceTargetFramework> in xml settings file. Also checked that rtcli.dll exists in path C:\Users\skalm\.nuget\packages\reinforced.typings\1.5.3\tools\netcoreapp2.2

**Comment by pavel-b-novikov** [comment]
Need more details about your project configuration. Check that project's TargetFramework set correctly

**Comment by skalma** [comment]
From the .csproj file:

<PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
    <TypeScriptToolsVersion>3.0</TypeScriptToolsVersion>
  </PropertyGroup>

Do you need any other information?

**Comment by pavel-b-novikov** [comment]
Still not clear. Try to follow steps suggested [here](https://github.com/reinforced/Reinforced.Typings/issues/35) regarding redirecting msbuild's output into txt file. It would help to identify problem

**Comment by skalma** [comment]
Will post results tomorrow, busy evening ahead. Just a thought: can i invoke typings build from package manager console using dotnet cmd? Test if that works...

**Comment by pavel-b-novikov** [comment]
Well, technically you can, but practically it is difficult. To build project from cmd is much easier

**Comment by skalma** [comment]
Output msbuild:

```
Task "CallTarget"
1>    Target ReinforcedTypingsGenerate:
1>      Using "RtCli" task from assembly "C:\Users\skalm\.nuget\packages\reinforced.typings\1.5.3\build\net46\Reinforced.Typings.Integrate.dll".
1>      Task "RtCli"
1>        C:\Program Files\dotnet\dotnet.exe "C:\Users\skalm\.nuget\packages\reinforced.typings\1.5.3\tools\netcoreapp2.2\rtcli.dll" profile "C:\Users\skalm\AppData\Local\Temp\tmp4D03.tmp"
1>        It was not possible to find any compatible framework version
1>        The specified framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
1>          - Check application dependencies and target a framework version installed at:
1>              C:\Program Files\dotnet\
1>          - Installing .NET Core prerequisites might help resolve this problem:
1>              https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
1>          - The .NET Core framework and SDK can be installed from:
1>              https://aka.ms/dotnet-download
1>          - The following versions are installed:
1>              2.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
1>              2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
1>              2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
1>              2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
1>              2.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
1>              2.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
1>              2.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
1>              2.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
1>        C:\Users\skalm\.nuget\packages\reinforced.typings\1.5.3\build\Reinforced.Typings.targets(59,3): error MSB6006: "" exited with code -2147450730.
1>      Done executing task "RtCli" -- FAILED.
1>    Done building target "ReinforcedTypingsGenerate" in project "TVC_DATA.csproj" -- FAILED.
1>  Done executing task "CallTarget" -- FAILED.
1>Done building target "CoreCompile" in project "TVC_DATA.csproj" -- FAILED.
```
2.2 is indeed not available in  C:\Program Files\dotnet. However, i did install the sdk and i am able to target .net core 2.2 in visual studio. Now struggling to find out where it is installed and how i can get it available in C:\Program Files\dotnet. Or am i going in the wrong direction here? Looks like it is not reinforced.typings related but if you have any ideas?

**Comment by skalma** [comment]
Ok solved it, i had installed the x86 version i.o. the x64 version of .net core sdk. Unistalling x86 and installing the x64 version solved it. Thanks for your time, sorry i bothered you with this!
