### ISSUE TITLE
Multiple Files not working in Version > 1.5.0

### ISSUE THREAD

**Issue by DaveLaa** [reinforced/Reinforced.Typings#135]
I tried to go back to 1.5.0 and all works. But with 1.5.3 (latest atm) rt generates only one file. What are the changes in latest versions? Version history is not updated...

**Comment by DaveLaa** [comment]
Sorry it all works fine. You have to close solution and reopen it after editing Reinforced.Typings.settings.xml file. Then changes are reread and eveything works fine.

**Comment by pavel-b-novikov** [comment]
Noted it in documentation, thanks.
