### ISSUE TITLE
RemoveTypeScriptStep is not working properly.

### ISSUE THREAD

**Issue by dashkodo** [reinforced/Reinforced.Typings#136]
Now it is removing CompileTypeScript and  CompileTypeScriptWithTSConfig from build pipelines
and call them later, but it do nothing with GetTypeScriptOutputForPublishing.

It breaks publish pipeline because GetTypeScriptOutputForPublishing collect zero output from CompileTypeScriptXXX targets.

Expected result: ReinforcedTypingsGenerate target will call GetTypeScriptOutputForPublishing  too after CompileTypeScriptXXX targets

**Comment by dashkodo** [comment]
Workaround:
`<Target Name="DisableTypeScriptPublish" AfterTargets="ConditionallyDisableTypeScriptCompilation">
    <Message Text ="$(CompileDependsOn)" />
    <ItemGroup>
      <CompileDependsOnTargets Include="$(CompileDependsOn.Split(';'))"/>
      <CompileDependsOnTargets Remove="GetTypeScriptOutputForPublishing"/>
    </ItemGroup>
    <PropertyGroup>
      <CompileDependsOn>@(CompileDependsOnTargets)</CompileDependsOn>
    </PropertyGroup>
    <Message Text ="$(CompileDependsOn)" />

  </Target>`

**Comment by dashkodo** [comment]
Also when calling 
`
<MSBuild Projects="$(MSBuildProjectFullPath)" Properties="INeedThis=JustToRebuildTypescripts;BuildingProject=true" Targets="CompileTypeScriptWithTSConfig" Condition="'$(TypeScriptTarget)' != '' AND '@(ConfigFiles)' != ''" />
`
from ReinforcedTypingsGenerate  - MSBUILD context is not shared and  @(ConfigFiles) keeps empty and as result - no output.

**Comment by pavel-b-novikov** [comment]
Well, in version 1.5.4 I have removed `GetTypeScriptOutputForPublishing` also from targets. Please check it and contact me if anything works not like expected
