### ISSUE TITLE
Typename in generated property

### ISSUE THREAD

**Issue by gabriel-ecegi** [reinforced/Reinforced.Typings#138]
Hello,
is there any option to generate type name as property for TS code?
Thing is Newtonsoft JSON can generate type name to property

```json
{
    "$type": "Company.CustomProject.Domain.Dtos.EntityDto, Company.CustomProject.Domain",
    "entityID": 1
}
```

It would be useful to have option to have this propery in generated type as 

```typescript
export interface EntityDto
{
    $type: "Company.CustomProject.Domain.Dtos.EntityDto, Company.CustomProject.Domain";
    entityID: number;
}
```

**Comment by smkanadl** [comment]
I haven't found a build-in way, but it was pretty easy to build on my own.

I add a private property called `JsonType` to each dto where I need the `$type`.

```
public class EntityDto
{
    public int EntityID { get; set; }

    private string JsonType { get; set; }
}
```

Then I use a builder to customize this property on export.

 ```
WithProperties(
    p => p.Name == "JsonType",
    c =>
    {
        c.OverrideName("$type");
        c.InferType(_ => "\'" + c.Member.DeclaringType + "\'");
        c.Order(-100);
    }
)
```

You need to make sure the interfered type matches your NewtonSoft serializer conventions and the Order is important to ensure the `$type` is always the first property in the object/interface.

**Comment by gabriel-ecegi** [comment]
@smkanadl Thanks for answer, but this is not preferred way for our codebase. Adding this property to c# class is like adding dependency on Reinforced.Typings to our domain. If we stop using Reinforced.Typings this property would be useless.

**Comment by smkanadl** [comment]
@gabriel-ecegi I had exactly the same thoughts and concerns. But as the property can be private, I found it more useful to have the types in the interface rather than worry about a property which can be easily removed if not needed any more. 

I used http://type.litesolutions.net/ before which allowed some clever side effect hacking to attach properties to an interface, but I did not found a way to make it work with Reinforced.Typings.

But of course I would like to have an even better solution :-)

**Comment by pavel-b-novikov** [comment]
No time to answer. 
Please consider overriding of code generator. Reference sample can be found [here](https://stackoverflow.com/questions/51604955/configuring-reinforced-typings-to-extend-a-class-unrelated-to-server-inheritence)

Please use Stackoverflow for such questions

**Comment by gabriel-ecegi** [comment]
@pavel-b-novikov Thank you for answer, but interfaces can have constant values 


If anyone is interested here is implementation.

``` csharp
public class TypeNameGenerator: InterfaceCodeGenerator
    {
        public override RtInterface GenerateNode(Type element, RtInterface result, TypeResolver resolver)
        {
            var baseCode = base.GenerateNode(element, result, resolver);

            var fullName = Context.CurrentBlueprint.Type.FullName;
            var projectName = Context.CurrentBlueprint.Type.Assembly.GetName().Name;

            var type = new RtRaw($"$type: \"{fullName}, {projectName}\"");
            
            baseCode.Members.Add(type);

            return baseCode;
        }
    }
```

**Comment by pavel-b-novikov** [comment]
TS Syntax cnahges faster than I can track it :(
