### ISSUE TITLE
error build NETStandard2.1

### ISSUE THREAD

**Issue by Gorniv** [reinforced/Reinforced.Typings#139]
Reinforced.Typings : Build warning RT0099: Assembly netstandard from C:\Program Files\dotnet\shared\NETStandard.Library\2.1.0\netstandard.dll was not loaded: System.IO.FileNotFoundException: Could not load file or assembly 'C:\Program Files\dotnet\shared\NETStandard.Library\2.1.0\netstandard.dll'. The system cannot find the path specified.
1>Reinforced.Typings : Unexpected error RT0999: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

**Comment by pavel-b-novikov** [comment]
Profile & log please

**Comment by Gorniv** [comment]
update  Reinforced.Typings.settings.xml
```xml
<RtDisable>false</RtDisable>
<!--fix for .netstandart2.1-->
<RtForceTargetFramework>netcoreapp3.0</RtForceTargetFramework>
```
