### ISSUE TITLE
How do I build this project?

### ISSUE THREAD

**Issue by Daniel15** [reinforced/Reinforced.Typings#143]
The signing key isn't in the repo, so running the build script complains that `Reinforced.snk` is missing. Are there directions on how to build this project myself?

**Comment by pavel-b-novikov** [comment]
Obviously it is noc contained within repo because it is my private key :) You can [create your key pair](https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-public-private-key-pair), rename it into `Reinforced.snk` and put into repo's root

**Comment by Daniel15** [comment]
Note that it's common for open-source projects to commit the key to source control. See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

> There are three major problems that developers run into after strong naming their assemblies:
> ...
> No drop-in replacement. This is a problem for open source libraries where the strong-name private key is not checked into the repository. This means that developers are unable to build to their own version of the library and then use it as a drop-in replacement without recompiling all consuming libraries up stack to pick up the new identity. This is extremely problematic for libraries, such as Json.NET, which have large incoming dependencies. Firstly, we would recommend that these open source projects check-in their private key (remember, [strong-names are used for identity, and not for security](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies)). 

I ended up just commenting out the `AssemblyKeyFile` in `Reinforced.Typings/Sign.cs` to compile a non-strong-signed version.
