### ISSUE TITLE
RT does nothing in VS2019 + .NET Core 2.2

### ISSUE THREAD

**Issue by NinjaCross** [reinforced/Reinforced.Typings#144]
Hi.
RT works perfectly within ALL my projects targeting .NET Framework, but does nothing in my project targeting .NET Core 2.2 on VS 2019 (version 16.3.6)
The file **Reinfroced.Typings.settings.xml** is in the root of the project. (Build Action = None, Copy to output Directory = Copy Always / Do Not Copy).

I'm getting some warnings about the content of the configuration file (see below), but I don't think they are related to the problem.

> Warning		The element 'PropertyGroup' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003' has invalid child element 'RtTargetFile' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003'

> Warning		The element 'ItemGroup' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003' has invalid child element 'RtAdditionalAssembly' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003'.

> Warning		The element 'Project' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003' has incomplete content.

I tried both fluent configuration and attributes-based configuration.
Using fluent configuration i can confirm that the configuration method is never called (i added a Console.WriteLine, and set the verbosity to "Diagnostic" to ensure getting something into the log).
It seems it's simply been ignored by the compiler.
I also tried closing all instances of Visual Studio, restarting the machine... etc.
I would like to give you more information, but since it's a very strange (and rare) scenario, I'm not sure how I can diagnose the problem.
Can you give some hints ?

**Comment by pavel-b-novikov** [comment]
Please show your Reinfroced.Typings.settings.xml file

**Comment by NinjaCross** [comment]
This configuration file has been created from the template generated by the NuGet package into my *.NET Core* project.
Since I couldn't find a way to make it work in *.NET Core*, I placed it into a *.NET Framework* project, and it's working perfectly !

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <RtTargetFile>$(ProjectDir)\..\MyCustomer.MyProject.WebSite\wwwroot\Models\MyCustomer.MyProject.Entities.ts</RtTargetFile>
    <RtConfigurationMethod>MyCustomer.MyProject.ReinforcedTypings.ReinforcedTypingsFluentConfiguration.Configure</RtConfigurationMethod>
    <RtDivideTypesAmongFiles>false</RtDivideTypesAmongFiles>
    <RtTargetDirectory>$(ProjectDir)\..\MyCustomer.MyProject.WebSite\wwwroot\Models\</RtTargetDirectory>
    <RtBypassTypeScriptCompilation>false</RtBypassTypeScriptCompilation>
    <RtDisable>false</RtDisable>
  </PropertyGroup>
</Project>
```

**Comment by pavel-b-novikov** [comment]
Hm.. One and only assumption is that you use outdated project.json, but it does not seems so. I have created fresh .net core 2.2 project in my VS 2019 and it worked properly.

**Comment by pavel-b-novikov** [comment]
RT does not support project.json, yes. 
And it even does not work on freshly created project?

**Comment by NinjaCross** [comment]
No, it doesn't work even into a freshly created project.
Could you please attach a .NET Core 2.2 project that works, so I can do a differential analysis and (maybe) understand what's missing/wrong with mine ?

**Comment by NinjaCross** [comment]
@pavel-b-novikov any news on this ?

**Comment by pavel-b-novikov** [comment]
Can't get my hands on it still :( Will give you feedback tomorrow

**Comment by pavel-b-novikov** [comment]
[RtTestWebProject.zip](https://github.com/reinforced/Reinforced.Typings/files/3787039/RtTestWebProject.zip)

Here is it

**Comment by pavel-b-novikov** [comment]
@NinjaCross Any new?

**Comment by NinjaCross** [comment]
@pavel-b-novikov Sorry, i'm out of town for a couple of days. I'll take a look at It ASAP.

**Comment by CodingPhantoms** [comment]
If there is any news, please post it :) Thank you 👍

**Comment by Daniel15** [comment]
Interesting... I'm using VS2019 and .NET Core 2.2 and it's working fine for me. I haven't open-sourced this particular project yet though.

**Comment by NinjaCross** [comment]
@pavel-b-novikov I compared your sample sources with mine, and there are no discernible differences.
That's indeed very odd.
Is there a log or something I can look at to check/diagnose the situation ?

**Comment by pavel-b-novikov** [comment]
@NinjaCross Seems like problem is on your machine only. Try it somewhere else - e.g. borrow laptop  colleague's laptop :)

**Comment by NinjaCross** [comment]
@pavel-b-novikov thanks for the feedback.
The problem is occurring in all the machines I tested.
So, there are no logs generated by RT I could check for errors or problems ?

**Comment by pavel-b-novikov** [comment]
Well, if it is not being launched then no logs except common msbuild /v:d logs, but I'm not sure.

**Comment by Martin-Praznovsky** [comment]
Have you been able to solve this issue? I have a project which when opened in VS2017 everything works perfectly fine, but when I open the same project in VS2019 then RT does nothing, looks like it is not being called at all during build.

**Comment by pavel-b-novikov** [comment]
@Martin-Praznovsky See my answer above. I cannot proceed without detailed log output
