### ISSUE TITLE
Nullable properties should automatically be nullable in resulting TypeScript type

### ISSUE THREAD

**Issue by Daniel15** [reinforced/Reinforced.Typings#145]
C# adds a feature called [nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references), which lets you specify that reference types can be null. For example:

```csharp
	[TsInterface(AutoI = false)]
	public class IpData
	{
		public string? City { get; set; }

		public string? Country { get; set; }

		public string? CountryIso { get; set; }

		public string? HostName { get; set; }
	}
```

However, in the resulting TypeScript type, the fields are **not** nullable:

```typescript
export interface IpData
{
	city: string;
	country: string;
	countryIso: string;
	hostName: string;
}
```

Reinforced.Typings should automatically infer that nullable fields can be nullable in the TypeScript type. Currently I need to manually add `ForceNullable`, which is redundant

```csharp
	[TsInterface(AutoI = false)]
	public class IpData
	{
		[TsProperty(ForceNullable = true)]
		public string? City { get; set; }

		[TsProperty(ForceNullable = true)]
		public string? Country { get; set; }

		[TsProperty(ForceNullable = true)]
		public string? CountryIso { get; set; }

		[TsProperty(ForceNullable = true)]
		public string? HostName { get; set; }
	}
```

**Comment by resolritter** [comment]
Had a look at the code. Nothing too decisive but hopefully it can at least serve as food for thought for the next reader.

I found two lines where Nullable nodes are supposedly handled

https://github.com/reinforced/Reinforced.Typings/blob/406967416ae3c78fbdf6bd69fe1add5a3dd31f52/Reinforced.Typings/Visitors/TypeScript/TypeScriptExportVisitor.RtIdentifier.cs#L11

https://github.com/reinforced/Reinforced.Typings/blob/d11a460f79ca646ca20ee7ee03c3ff52b5c39d06/Reinforced.Typings/Ast/RtIdentifier.cs#L58

As well as this line which tests for Nullables

https://github.com/reinforced/Reinforced.Typings/blob/9fbc5468d5b6ef62369cb05fb0d758b65b908b9e/Reinforced.Typings/TypeResolver.cs#L244

After that I went into the tests folders to see if there were cases covering those lines, but couldn't find any. The current tests verify the behaviour of **forced** nullable, but apparently not arbitrary "natural" nullables.

**Comment by pavel-b-novikov** [comment]
> I found two lines where Nullable nodes are supposedly handled
The first 2 are wrong. 3rd line is correct. The thing is inside IsNullable extension method:

https://github.com/reinforced/Reinforced.Typings/blob/9fbc5468d5b6ef62369cb05fb0d758b65b908b9e/Reinforced.Typings/TypeExtensions.cs#L472

And it actually consists of single line which obviously is not what supposed:

https://github.com/reinforced/Reinforced.Typings/blob/9fbc5468d5b6ef62369cb05fb0d758b65b908b9e/Reinforced.Typings/TypeExtensions.cs#L474

Right now I'm not sure how to identify `string?` via reflection. Would appreciate help.

**Comment by resolritter** [comment]
I found this [interesting blog post](https://blog.rsuter.com/the-output-of-nullable-reference-types-and-how-to-reflect-it/) and it was funny to see that it changed a few times. : ^ )

At the bottom, it points to the latest resolution which is https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md.

And in the comments, the author publicizes this library: https://github.com/RicoSuter/Namotion.Reflection.

I'd like to try to fix this but I don't code in C# (i.e. I don't have the debugging symbols stuff ready). I'll try to manage with prints later today.

**Comment by pavel-b-novikov** [comment]
@resolritter Highly appreciate :)

**Comment by resolritter** [comment]
Hi @pavel-b-novikov . From the other library I've mentioned in my previous post, I believe I've found a the place which determines type nullability.

https://github.com/RicoSuter/Namotion.Reflection/blob/ac6d21324646a135380a5b2f0c21826bc1d64706/src/Namotion.Reflection/Context/ContextualType.cs#L202

Question is: are you fine with bringing that library as a dependency, or would you rather just bring in that part of the code?

Also I've noticed that library uses a repository you don't have in this project ([Roslyn-related](https://github.com/RicoSuter/Namotion.Reflection/blob/eabfd9a189953875b3fa0e2c08a20b41de47766f/src/nuget.config)) so I'm unsure currently if it's compatible with what you're doing here.

**Comment by johnknoop** [comment]
Hi! I'm looking to replace TypeWriter because it doesn't handle nullable reference types. This thread indicates that RT doesn't either. Is this correct?

**Comment by Daniel15** [comment]
@johnknoop It works fine in RT if you explicitly annotate the fields with `ForceNullable`:
```
[TsProperty(ForceNullable = true)]
public string? City { get; set; }
```

**Comment by johnknoop** [comment]
@Daniel15 Is that the only way? If I adopt RT, I was more attracted by the fluent configuration than the attribute-based.

**Comment by pavel-b-novikov** [comment]
> @Daniel15 Is that the only way?

`.WithProperty(...).ForceNullable()`

**Comment by johnknoop** [comment]
@pavel-b-novikov will this have to be done case by case, or is there some way to do it globally?

**Comment by pavel-b-novikov** [comment]
@johnknoop You have all the powers of fluent configuration. So you can use mix of `.ExportAsInterfaces`/`.WithProperties(...)` to propagate it globally. 

Please note that you still have to disinguish nullable reference types by yourself in this case.

**Comment by johnknoop** [comment]
@pavel-b-novikov that sounds promising! Is it ok if I just check a few things more with you so that I know whether or not I could switch over to RT seamlessly without breaking my TS build? These are the quirks I need:

- [ ] Match C# files by namespace (or, failing that, by folder)
- [ ] One TS file for every C# file (meaning sometimes there will be multiple TS interfaces in the same file)
- [ ] If the C# class has a base class, then all those properties must also be included
- [ ] Ability to map custom types, so that I can configure it to generate `Date` for all NodaTime types.
- [ ] Enums should become discriminated unions
- [ ] All nullables, even nullable reference types, should produce optional TS properties
- [ ] Whenever a C# class has a property of a type that is defined another C# code file, that type should also be included in the same TS file
- [ ] Don't produce any namespaces (all TS types should be `export`ed so that the file becomes a module

If I can tick all those boxes, then I can switch over to RT with very little effort.

**Comment by pavel-b-novikov** [comment]
> Match C# files by namespace (or, failing that, by folder)

Not sure if I've got the thought, but basically you can point RT to any set of `Type`s with fluent configuration - `.ExportAsInterfaces` also consume `IEnumerable<Type>`

> Enums should become discriminated unions

Achievable with custom code generator/visitor override

> Whenever a C# class has a property of a type that is defined another C# code file, that type should also be included in the same TS file

As mentioned above you can point to `IEnumerable` of types for sure and set up files decomposition (RT will automatically add necessary `import`s). So this is definitaly solveable, but I cannot say how much effort it require

**Comment by johnknoop** [comment]
> As mentioned above you can point to IEnumerable of types for sure and set up files decomposition (RT will automatically add necessary imports). So this is definitaly solveable, but I cannot say how much effort it require

Is it possible to not get them imported into the TS file but actually defined in there instead? So if the C# class to transform is called `Car` and has a property of type `Brand` then the resulting TS file will contain both the `Car` and the `Brand` interfaces?

**Comment by pavel-b-novikov** [comment]
It is possible, but requires some manual work

**Comment by johnknoop** [comment]
Thats perfectly fine. As long as it's documented somewhere what I need to do, then I don't mind playing around with it for a while :) Do you know if this is covered in the wiki?

**Comment by pavel-b-novikov** [comment]
[`ExportTo` is one that you need](https://github.com/reinforced/Reinforced.Typings/wiki/Fluent-configuration#interface).

Also please refer to [tests](https://github.com/reinforced/Reinforced.Typings/tree/master/Reinforced.Typings.Tests/SpecificCases) - there are pretty much weird cases covered.

**Comment by johnknoop** [comment]
Thanks! That should get me started.

**Comment by Snazzie** [comment]
Hi guys, so im battling the nullability through reflection. 
```csharp
var isNullabe = Nullable.GetUnderlyingType(typeof(GroupDto).GetField(e.Member.Name).FieldType);
if (isNullabe != null)
{
    e.OverrideName(e.Member.Name + "? ");
}
```

This apparently should be able to handle `?` but im getting the following exception.

`Error RT0999: Exception thrown when applying fluent configuration method for type '....GroupDto': Exception thrown when applying fluent configuration method for property '....GroupDto.ParentId': Object reference not set to an instance of an object.`

```csharp
public class GroupDto
{
     public Guid? ParentId { get; }
}

**Comment by Snazzie** [comment]
Hey guys, using reflection. I am able to handle `?`. See following working code. Hopefully this helps the maintainer to add auto `?` handling. 😄 

```csharp
using System;
using System.Linq;
using System.Reflection;
using Reinforced.Typings.Ast.TypeNames;
using Reinforced.Typings.Fluent;

namespace ReinforcedTypings
{
    public static class ReinforcedTypingsConfiguration
    {
        public static void Configure(ConfigurationBuilder builder)
        {
            const string responseNamespace = "Api.Dto.Response";

            // fluent configuration goes here
            var dtos = Assembly.GetExecutingAssembly().GetTypes()
                .Where(x => x.Namespace == "Api.Dto")
                .ToArray();

            builder
                .Substitute(typeof(Guid), new RtSimpleTypeName("string"))
                .Substitute(typeof(DateTime), new RtSimpleTypeName("Date"));

            builder.ExportAsEnums(
                dtos.Where(e => e.IsEnum),
                conf => conf
                    .FlattenHierarchy()
                    .OverrideNamespace(responseNamespace));

            foreach (var type in dtos.Where(e => e.IsClass))
            {
                builder.ExportAsInterfaces(
                    new[] { type },
                    conf =>
                    {
                        conf.FlattenHierarchy()
                        .WithPublicProperties(
                            e =>
                                    {

                                        var isNullabe = Nullable.GetUnderlyingType(type.GetProperty(e.Member.Name).PropertyType);
                                        if (isNullabe != null)
                                        {
                                            e.OverrideName(e.Member.Name + "? ");
                                        }

                                    })
                        .WithPublicFields(
                            e =>
                                    {
                                        var isNullabe = Nullable.GetUnderlyingType(type.GetField(e.Member.Name).FieldType);
                                        if (isNullabe != null)
                                        {
                                            e.OverrideName(e.Member.Name + "? ");
                                        }
                                    })
                        .AutoI(false)
                        .OverrideNamespace(responseNamespace);

                    });
            }

        }
    }
}
```

**Comment by pavel-b-novikov** [comment]
But it already automatically handles nullable value types.

**Comment by Snazzie** [comment]
It hasnt generated any nullable typescript for me. Maybe its working for `Nullable<T>`. but not for `T?`. Not for me anyway.

**Comment by nros** [comment]
I have created a unit test case for this problem, showing, that the nullable value is not properly handled by default - at least  if if C# 8.0 "nullable"-feature is used.

https://gist.github.com/nros/558ba0d0afb638dea20d5821bb411f98

Using the library [Namotion.Reflection](https://github.com/RicoSuter/Namotion.Reflection), this can be fixed. The library seems to be provided and used by NSwag. Would it be OK to use it?

The fix would be in Type extension function `IsNullable()`.

**Comment by pavel-b-novikov** [comment]
No 3rd party dependencies.

**Comment by nros** [comment]
OK, understandable. Then let's figure it out, how NSwag did it ...
