### ISSUE TITLE
Support for .Net Core 3.1

### ISSUE THREAD

**Issue by abritabroad** [reinforced/Reinforced.Typings#152]
Getting this error with the new docker images:
"/root/.nuget/packages/reinforced.typings/1.5.5/build/Reinforced.Typings.targets(59,3): error MSB6006: "" exited with code 1.".
The good news is: v3.1 is a LTS version so should be good for three years :)

**Comment by ilya-uryupov** [comment]
For anyone looking for a temporary fix - this has worked for me:
1) copy the folder `C:\Users\{USER}\.nuget\packages\reinforced.typings\1.5.5\tools\netcoreapp3.0` and rename it to `netcoreapp3.1`
2) inside the new folder update `rtcli.runtimeconfig.json`:
```diff
{
  "runtimeOptions": {
-    "tfm": "netcoreapp3.0",
+    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
-      "version": "3.0.0"
+      "version": "3.1.0"
    }
  }
}
```
3) update `rtcli.deps.json`:
```diff
{
  "runtimeTarget": {
-    "name": ".NETCoreApp,Version=v3.0",
+    "name": ".NETCoreApp,Version=v3.1",
    "signature": ""
  },
  "compilationOptions": {},
  "targets": {
-    ".NETCoreApp,Version=v3.0": {
+    ".NETCoreApp,Version=v3.1": {
      "rtcli/1.0.0": {
```
4) build tasks should work properly now.

**Comment by abritabroad** [comment]
yay! I made those changes to my Windows folder which fixed Visual Studio, then copied that whole folder to docker at /root/.nuget/packages/reinforced.typings/1.5.5/tools/netcoreapp3.1/ and it fixed the build! Cheers :)

**Comment by loedeman** [comment]
Nice workarounds. However, keep in mind that a build server does not work with those workarounds (and it's frustrating for your colleagues :-))... A fix would be very welcome!

**Comment by loedeman** [comment]
Created PR #153 which should permanently solve this issue.

**Comment by thombrink** [comment]
PR #154

**Comment by abritabroad** [comment]
> Nice workarounds. However, keep in mind that a build server does not work with those workarounds (and it's frustrating for your colleagues :-))... A fix would be very welcome!

It works on a build server if your CI pipeline is docker-based :)

**Comment by mraouf** [comment]
When this is expected to be released (Available in Nuget)?

**Comment by pavel-b-novikov** [comment]
I will do my best to proceed next week

**Comment by targetpnovikov** [comment]
Damit! For some reason I cannot build it with netcore 3.1

**Comment by pavel-b-novikov** [comment]
Done

**Comment by DBalashov** [comment]
.net 5.0 release:

![10_211129](https://user-images.githubusercontent.com/2083946/98699935-73850d00-2399-11eb-9f1f-db3bab0967f8.png)

**Comment by nvirth** [comment]
Same here. The path to the `exe` is wrong, it contains `net5.0`, but that should be `net5`

**Comment by nvirth** [comment]
Solved by changing the target framework from `net5` to `net5.0` in csproj:

    <TargetFrameworks>net48;net5</TargetFrameworks>
    <TargetFrameworks>net48;net5.0</TargetFrameworks>

**Comment by Logerfo** [comment]
This issue probably has to do with the following: https://github.com/reinforced/Reinforced.Typings/blob/ef3aaf3713affd3ec277c705548f39074122b519/cake/build.cake#L35-L36

Allowing both `net5` and `net5.0` (and do the same for `net6`) should do the trick, but there're probably more available options and the casing should be insensitive.
