### ISSUE TITLE
Unable to switch model generation based on msbuild property

### ISSUE THREAD

**Issue by natanielcz** [reinforced/Reinforced.Typings#157]
I've set environment variable in launchSettings.json to:
```json
"environmentVariables": {
            "ASPNETCORE_ENVIRONMENT": "Development",
            "ASPNETCORE_ENVIRONMENT": "false"
        },
```

and rt settings to:
`<RtDisable>$([MSBuild]::ValueOrDefault(CONTINUOUS_INTEGRATION, true))</RtDisable>`

but Reinforced.Typings are still not generating code locally. It can't see environment variable

**Comment by pavel-b-novikov** [comment]
I cannot comment since don't know the mechanism of `$([MSBuild]::)` construction

**Comment by natanielcz** [comment]
If I set `<RtDisable>$(CONTINUOUS_INTEGRATION)</RtDisable>` It still doesn't work

**Comment by pavel-b-novikov** [comment]
>I do not see where CONTINOUS_INTEGRATION variable comes from, therefore cannot comment in this
^

**Comment by natanielcz** [comment]
My bad. I just figured out that I have to pass parameters via the command line to make it work. You may close this issue
