### ISSUE TITLE
Support for const  export of static classes

### ISSUE THREAD

**Issue by fkpama** [reinforced/Reinforced.Typings#163]
Hello,

The RtClass exporter does not support exporting  a static class as const (or enum?).

This could be usefull for some use cases, as in to easily export constants to the client app (see code below). Furthermore when the C# static class to export is not owned by the end user

Is there any plan to support this? Or could you please advise a practical solution/alternative for the following code?

#### C# third party static class:
```
public static ThirdPartyAssemblyStaticType {
          public const string Foo = "bar";
}
```

#### C# fluent configuration method:
```
public static void ConfigureTypings(ConfigurationBuilder builder)    
{
     builder.ExportAsConst(typeof(ThirdPartyAssemblyStaticType));
 }
```

 #### Exported to/ Typescript code :
```
export const ThirdPartyAssemblyStaticType = {
       Foo: 'bar'
};
Object.freeze(ThirdPartyAssemblyStaticType);
```

**Comment by pavel-b-novikov** [comment]
You car create your own code generator to support this functionality. Please refer to [manual](https://github.com/reinforced/Reinforced.Typings/wiki/Code-Generators)
