### ISSUE TITLE
.Net 5.0 (Preview) Support

### ISSUE THREAD

**Issue by abritabroad** [reinforced/Reinforced.Typings#165]
Has anyone got the dotnet 5.0 preview working with RT?

I tried the techniques in the following thread with no success.

https://github.com/reinforced/Reinforced.Typings/issues/152

Steve

**Comment by pavel-b-novikov** [comment]
5.0?!! God damn, when this pot is going to stop to boil?!

**Comment by abritabroad** [comment]
Lol, sorry

**Comment by radiosterne** [comment]
@pavel-b-novikov as of today, .Net 5.0 is released. I've opened #188, which, to my knowledge, enables its support — I've tested it locally with one of my pet projects. I'd gladly provide any further testing and/or assistance with it, if needed

**Comment by abritabroad** [comment]
yay! thanks a lot 👍
