### ISSUE TITLE
Missing changelog since version 1.4.2 / 1.5

### ISSUE THREAD

**Issue by natanielcz** [reinforced/Reinforced.Typings#166]
Hi,

Great job with this tool! :) It provides huge customization capabilities. 

I wanted yesterday to do a quick check of what changed in the latest version but couldn't find a quick way to do that. Wiki shows version 1.5 as the latest and releases page shows version 1.4.2.

Could You please give us short information with a changelog? :)

**Comment by pavel-b-novikov** [comment]
Hi!
Updated [version history](https://github.com/reinforced/Reinforced.Typings/wiki/Version-history)

Some versions are missing, but I honestly try to keep it updated. Sorry

**Comment by natanielcz** [comment]
Thanks! :)

**Comment by pavel-b-novikov** [comment]
I have also [this folder](https://github.com/reinforced/Reinforced.Typings/tree/master/stuff/relnotes) - it contains history of release notes that is being automatically included into `nupkg`. It certainly has the latest data.

**Comment by natanielcz** [comment]
So maybe It would be easier for you to redirect users on other pages to this directory? :) Just write a short note on releases page and in the wiki that release notes are available in this directory ;)
