### ISSUE TITLE
Code generator Reinforced.Typings.Generators.ClassCodeGenerator has thrown an error: Length cannot be less than zero.

### ISSUE THREAD

**Issue by urbanmichal** [reinforced/Reinforced.Typings#17]
Hi guys,

I've got compiler error: **"Code generator Reinforced.Typings.Generators.ClassCodeGenerator has thrown an error: Length cannot be less than zero."**

I'm using fluent configuration.

After building the project only ts.tmp file is generated and there's no ts file.

Everything worked properly before and I can't remember any source code change.

**Gist Github** with Reinforced.Typings.settings.xml and InterfacesBuilder.cs: https://gist.github.com/urbanmichal/6578576f42f9be2572c575fe5a9d7da5

I will be grateful for any help you can provide.

**Comment by pavel-b-novikov** [comment]
Will take a look today

**Comment by urbanmichal** [comment]
@pavel-b-novikov Thank you, I will check that.

**Comment by urbanmichal** [comment]
@pavel-b-novikov `RtRootNamespace` seems to be used when `RtDivideTypesAmongFiles` is true, in my case it's false (I'm using `RtTargetFile` for generating one ts file).

**Comment by pavel-b-novikov** [comment]
Why dont you use RtAdditionalAssembly in your .settings.xml?

**Comment by urbanmichal** [comment]
Ok, I know roughly what's wrong... I'll write later when I found out everything :-)
