### ISSUE TITLE
Async modifier support

### ISSUE THREAD

**Issue by eliottrobson** [reinforced/Reinforced.Typings#170]
The same way we have `RtFuncion.IsStatic` would it be possible to add `RtFuncion.IsAsync`?

`public async method(): Promise...`

For anyone else needing this it's possible to hack it by overriding the identifier, but this is far from ideal.

`result.Identifier = new RtIdentifier("async originalName");` or
`result.Identifier = new RtIdentifier("async " + result.Identifier.IdentifierName);`

**Comment by nros** [comment]
Seems to be implemented with commit c35f249c4a3a439dd559ef302db8ac9815463f0b, isn't it?

**Comment by eliottrobson** [comment]
Yeah, looks good to me!

**Comment by pavel-b-novikov** [comment]
Community force! :D
