### ISSUE TITLE
Hierarchical output structure

### ISSUE THREAD

**Issue by vl-bwalocha** [reinforced/Reinforced.Typings#171]
Hi!

Is it possible to set `Herarchical` directory output structure for generated TS models using MSBuild? I can see [property](https://github.com/reinforced/Reinforced.Typings/blob/406967416ae3c78fbdf6bd69fe1add5a3dd31f52/Reinforced.Typings/ExportContext/ExportContext.Configurables.cs#L17) for it but how to set it via fluent settings or in XML?
Is the functionality available only in CLI?

cheers!

**Comment by pavel-b-novikov** [comment]
It is by default hirarchical. `RtTargetDirectory` + `RtDivideTypesAmongFiles` + `[TsGlobal(RootNamespace="...")]` will do the trick.

**Comment by pavel-b-novikov** [comment]
Stop asking questions in github

**Comment by vl-bwalocha** [comment]
I set `RtTargetDirectory`, `RtDivideTypesAmongFiles` and `[assembly:TsGlobal(RootNamespace = "XXX")]` but it does not work. This is why I post it here. Thanks.

**Comment by pavel-b-novikov** [comment]
Code please
