### ISSUE TITLE
Contents of Reinforced.Typings.settings.xml when using Fluent configuration

### ISSUE THREAD

**Issue by johnknoop** [reinforced/Reinforced.Typings#172]
Since I'm using fluent configuration, my Reinforced.Typings.settings.xml only contains this:

```xml
	<PropertyGroup>
	
		 <RtConfigurationMethod>MyApp.TypeDefinitions.Configure</RtConfigurationMethod>
		
	</PropertyGroup>
```

When I build, I get this in the log:
> Reinforced.Typings.settings.xml : warning : Reinforced.Typings will not run because it is disabled in its configuration

What is the minimum content I need to add to Reinforced.Typings.settings.xml when using fluent configuration?

**Comment by pavel-b-novikov** [comment]
Do not ask questsions through GitHub. Use StackOverflow please
