### ISSUE TITLE
Ability to pull types from assemblies

### ISSUE THREAD

**Issue by CBlaize** [reinforced/Reinforced.Typings#179]
Hey there, thanks for a pretty sweet nuget package.

I'm wanting to just pull all of my model types from a certain assembly like this:

```c#
public static void Configure(ConfigurationBuilder builder)
{
  var types = Assembly.GetExecutingAssembly().GetTypes().Where(t => t.IsClass && t.IsPublic && t.Namespace == "some namespace");
 
  builder.ExportAsInterfaces(types, config => config.WithPublicProperties());
}
```

However, it fails to build with error `exited with code -1073741571`.  I have a feeling it's failing to pull from the correct assemblies and is running outside of my main project's assemblies.

Have any insight into how I can get this to work?  I'll respond back if I find a solution as well.

**Comment by pavel-b-novikov** [comment]
[this](https://github.com/reinforced/Reinforced.Typings/blob/c8b21a79bcb4be33d6cffd1dba29314ce0fdd8e8/stuff/Reinforced.Typings.settings.xml#L84) ?

**Comment by CBlaize** [comment]
I saw that a few minutes after I posted this!

I did add references to my other projects, but maybe I am just still missing some references.

I'm now getting the following error.  `Unable to load one or more of the requested types`

If I have a class

```c#
public class Test
{
  public NuGet.Versioning.SemanticVersion SemanticVersion { get; set; }
}
```

Would I then need to include `NuGet.Versioning` as an additional assembly?

**Comment by pavel-b-novikov** [comment]
Unfortunately, yup

**Comment by CBlaize** [comment]
Not that big of a deal, just a little more manual setup. 
At least I know how to move forward, so thank you for your help.
