### ISSUE TITLE
Filtering methods

### ISSUE THREAD

**Issue by urbanmichal** [reinforced/Reinforced.Typings#18]
Hi guys,

Is there any way to generate methods, which name doesn't starts with "Begin" or "End" phrase?

**Pseudocode:**

.ExportAsInterfaces(proxyInterfaces, conf => conf.WithPublicMethods(publicMethod =>
				!publicMethod.GetType().Name.StartsWith("Begin")
				&&
				!publicMethod.GetType().Name.StartsWith("End")));

**Comment by pavel-b-novikov** [comment]
```
var types = new Type[0];
builder.ExportAsClasses(types,
	c => c.WithMethods(
		x => !(x.Name.StartsWith("Begin") || x.Name.StartsWith("End")),
		x=>x.Returns<string>()
		)
	);
```

**Comment by urbanmichal** [comment]
Work like a charm, thank you :) Działa pięknie, ja ponimaju trochę też ;) Closing!

**Comment by urbanmichal** [comment]
I've got minor problem with this solution:

x => x.Returns<string>()

Now, every interface has a string return type. Could we keep proper return type?

**Comment by pavel-b-novikov** [comment]
`x => x.Returns<string>()` - is just sample that you can configure export settings for bunch of methods. You can entirely remove this parameter of .WithMethods to make it simply export methods without additional actions.

**Comment by pavel-b-novikov** [comment]
`x => x.Returns<string>()` - is just sample that you can configure export settings for bunch of methods. You can entirely remove this parameter of .WithMethods to make it simply export methods without additional actions.

**Comment by urbanmichal** [comment]
Of course... Great, thanks :-)
