### ISSUE TITLE
How to remove module wrapping around exported types

### ISSUE THREAD

**Issue by Snazzie** [reinforced/Reinforced.Typings#181]
Is there a way to remove the module wrapping or so its interfaces can be imported? Im unable to get it working in the browser as everywhere its used it throws a `module is not defined` error. Turns out modules dont work in es5 in the browser.

### Current output
```js
module _your_namespace_ {
    export interface IOrderViewModel {	
        ItemName: string;			
    }
    export interface IOrderViewModel2 {	
        ItemName: string;			
    }

}

```

### Desired output
```js
export interface IOrderViewModel {	
     ItemName: string;			
}
export interface IOrderViewModel2 {	
     ItemName: string;			
}
```

**Comment by pavel-b-novikov** [comment]
[RTFM regarding `UseModules` with `discardNamespaces`](https://github.com/reinforced/Reinforced.Typings/wiki/Fluent-configuration#global-configuration-builder)

**Comment by Snazzie** [comment]
That section isnt really clear.

if 
`bool useModules = false`
`bool discardNamespaces = true`

id expect to get my behaviour, but thats not the case here, its going against the extension name and parameter names definition.

**Comment by pavel-b-novikov** [comment]
Set UseModules to true

**Comment by Snazzie** [comment]
That worked. Ok now i understand, UseModules doesnt refer to the actualy module keyword, it refers to the switch of module used...

I feel like external-facing code should be relatively self-explanatory. In this case, UseModules actually should determine if `module` appears in generated types. rather than some internal context switching.

Thanks for clarifying.

**Comment by pavel-b-novikov** [comment]
It actually refers to the times when TypeScript did not support imports/exports and class-per-file. So it left there for backward compatibility reasons
