### ISSUE TITLE
Support detection of "Task" return types of methods -> AutoAsync

### ISSUE THREAD

**Issue by nros** [reinforced/Reinforced.Typings#182]
Converting method declarations from an interface will fail with current detection of `async` function. As Interfaces only declare functions and do not implement these, the usage of "async" keyword is not possible and not reasonable. Asynchronous behaviour is an implementation detail and thus not directly part of the interface.

Nevertheless interfaces need to indicate such asynchronous implementation by defining the return value to be of type `Task`. TypeScript behaves exactly the same, using `Promise`  as required return type. So, when exporting an interface method that delcares a function with return value `Task`, then `Promise`  is needed to be used in TypeScript.

Using just a type mapping will fail as soon as a class is exported as an interface with `ExportAsInterfaces` and the method is defined with `async` keyword. Substitutions of Generics do not properly work either, as a simple return type of `Task` does not have any generics attached.

SInce `Task` is an integral part of C#, I think it should be supported out of the box.

**Comment by pavel-b-novikov** [comment]
You're welcome to create PR. It is relatively simple fix. I cannot get my hands on it for now.

**Comment by nros** [comment]
Here it is :)

**Comment by nros** [comment]
@pavel-b-novikov  did you have any time to look at the PR? I tried to rework it based on the link you have sent me. Does it fit your needs and requiremets now?
