### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by ADIX7** [reinforced/Reinforced.Typings#186]
Code generation does not work in F# projects.

**Comment by pavel-b-novikov** [comment]
F# support was not claimed and will not appear in near future.

**Comment by ADIX7** [comment]
Thanks. Actually I have managed to debug this there is no TargetsTriggeredByCompilation in FSharp msbuild targets. After adding that to the FSharp msbuild target it actually works and does generate the TS models.

**Comment by pavel-b-novikov** [comment]
Great. If you want to make it work on F# - feel free to send PRs

**Comment by ADIX7** [comment]
Unfortunately it needs a framework change.

I opened an issue https://github.com/dotnet/fsharp/issues/10141
