### ISSUE TITLE
.NET 5.0 support?

### ISSUE THREAD

**Issue by Daniel15** [reinforced/Reinforced.Typings#195]
I'm trying to upgrade one of my sites to .NET 5.0, and I'm getting this error when I try to build the site:

```
Error	MSB6004	The specified task executable location "C:\Users\Daniel\.nuget\packages\reinforced.typings\1.5.8\tools\net5.0\rtcli.exe" is invalid.	DnsTools.Web	C:\Users\Daniel\.nuget\packages\reinforced.typings\1.5.8\build\Reinforced.Typings.targets	59	
```

Any ideas?

**Comment by pavel-b-novikov** [comment]
Package with .net 5.0 support will be published soon. It is not published yet.

**Comment by Daniel15** [comment]
@pavel-b-novikov Is it OK if you keep this issue open until the new version is published? I'll use it to know when the update is available :)
