### ISSUE TITLE
Support records?

### ISSUE THREAD

**Issue by Daniel15** [reinforced/Reinforced.Typings#197]
I haven't been able to test this due to the lack of .NET 5.0 support (see #195) but it would be good to check that C# 9.0 record types are supported. https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#record-types

**Comment by pavel-b-novikov** [comment]
How do you see "support of records"?

**Comment by lindsve** [comment]
I'm aiming to try this when the new package is available, but as far as I can tell so far, it shouldn't be an issue. C# 9 records are syntactic sugar on top of regular classes, so as @pavel-b-novikov says, you probably should be able to use either .ExportAsClass or .ExportAsInterface

**Comment by pavel-b-novikov** [comment]
[Test](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.Records.cs)

**Comment by Daniel15** [comment]
Thank you!

**Comment by Daniel15** [comment]
When I use attributes, for example:
```
[TsInterface(AutoI = false, AutoExportMethods = false)]
public record LocationPingRequest
{
	public string Hello { get; init; }
}
```

I get a `equalityContract` property:
```
export interface LocationPingRequest
{
	equalityContract: any;
	hello: string;
}
```

Is there a way to avoid this, other than using `AutoExportProperties` and explicitly exporting the individual properties?

**Comment by MyEidos** [comment]
@Daniel15 
Try to use fluent configuration. 
Like this:
`    public static class ReinforcedTypingsConfiguration
    {
        public static void Configure(ConfigurationBuilder builder)
        {
            builder.Global(a => a.DontWriteWarningComment());
            builder.ExportAsInterface<CreateEmployeeRequest>().WithPublicProperties();
        }
    }`
