### ISSUE TITLE
Feature: Global dynamic type resolution

### ISSUE THREAD

**Issue by tonyhallett** [reinforced/Reinforced.Typings#201]
The fluent substitution is not suitable and although doable with InlineTypeInferers it would be useful to provide in one place a class that will be asked to resolve.  Either via fluent api or an attribute providing the type to instantiate.

**Comment by pavel-b-novikov** [comment]
There is already [TypeResolver](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings/TypeResolver.cs) for that. And global substitution works on top of it. There is absolutely no reason for additional abstraction - you can reach desired behavior by using global substitutions.

**Comment by tonyhallett** [comment]
@pavel-b-novikov Global substitutions allows for type mapping that I know ahead of time.  TypeResolver is sealed.   How do you suggest that I do something like the following - all C# nullable types to a new typescript type Nullable<T> ?
