### ISSUE TITLE
Unnecessary build warnings

### ISSUE THREAD

**Issue by dcowen91** [reinforced/Reinforced.Typings#213]
AssemblyManager.cs has a 3 places where it logs extra warnings than necessary - lines 78, 151, and 188. Can these be converted to regular log messages instead of warnings? Or can we add custom warning suppression support? I could see that being possible as a new property in Reinforced.Typings.settings.xml. I am happy to raise a PR for either of these approaches.

**Comment by pavel-b-novikov** [comment]
Warning suppression mechanism delivered: `RtSuppress` in Reinforced.Typings.settings.xml
