### ISSUE TITLE
DateTime -> any

### ISSUE THREAD

**Issue by urbanmichal** [reinforced/Reinforced.Typings#22]
Is it by design that DateTime C# type are translated to any type in TypeScript?

**Comment by pavel-b-novikov** [comment]
Exactly. Because JSON (to generate models for RT is being used for almost 95% of cases) does not contain literal dates type. Date serialization way depends on exact JSON serializer. jsDate is not the best type for this case also.
So the bes solution is to leave it as is and let target used decide.

**Comment by urbanmichal** [comment]
Yeap, I thought so. It makes sense, thanks for answer! :-)
