### ISSUE TITLE
Could we declare TypeScript type for given C# type using FluentConfiguration?

### ISSUE THREAD

**Issue by Crozin** [reinforced/Reinforced.Typings#23]
Is there any way we could inform Reinforced.Typings to use `string` TS-type for `System.Guid` C#-type? Right now `TypeResolver` outputs `RTW0003_TypeUnknown` warning and assumes `any` TS-type.

**Comment by pavel-b-novikov** [comment]
Project-wide - no. 
But you can manually override type for particular property/field/parameter/return value/generic parameter

**Comment by pavel-b-novikov** [comment]
Substitutions are implemented in 1.30 branch according to your request.
Please check out this branch and run your test

**Comment by pavel-b-novikov** [comment]
Fixed in 1.3.0
