### ISSUE TITLE
Generated typescript enum doesn't output all keys correctly when there are duplicate enum values

### ISSUE THREAD

**Issue by ysavoie-lavigueur** [reinforced/Reinforced.Typings#24]
We came across this issue for some of our bitfield enums. For example, here is a enum that would pose problem:
```
	[Flags] [TsEnum(IncludeNamespace = false)]
	public enum UserGroup
	{
		None				= 0x00,
		Administrator			= 0x01,
		Standard				= 0x02,
		Restricted			= 0x04,
		Guest				= 0x08,
		RestrictedAndLower	= Restricted | Guest,
		Default				= Standard,
	}
```
and here is the Typescript generated:
```
export enum UserGroup {
	None = 0,
	Administrator = 1,
	Standard = 2,
	Standard = 2,
	Restricted = 4,
	Guest = 8,
	RestrictedAndLower = 12,
}
```

(Notice the the `Standard` key is duplicated and the `Default` key is missing)

**Comment by pavel-b-novikov** [comment]
I've merged your pull request. 
Big thanks! You helped me a much.
Will provide you with beer in case of IRL meeting. :)

**Comment by ysavoie-lavigueur** [comment]
Happy to help! Thanks for the development of this great tool :)
