### ISSUE TITLE
.Net 7 Compatibility please!

### ISSUE THREAD

**Issue by abritabroad** [reinforced/Reinforced.Typings#246]

**Comment by abritabroad** [comment]
yay!

**Comment by pavel-b-novikov** [comment]
I will try to build and publish new version as soon as possible

**Comment by pavel-b-novikov** [comment]
Pic related: "What?! Again?!"

![image](https://user-images.githubusercontent.com/2521412/200951932-49b6266d-2424-4183-894e-64a5809ddf2d.png)

**Comment by abritabroad** [comment]
The only constant in software development is change. 'Jared Huckaby'
