### ISSUE TITLE
Add raw line to output file (for example to disable eslint errors)

### ISSUE THREAD

**Issue by obriankevin11** [reinforced/Reinforced.Typings#252]
Hi,

I have this:

c#
```
public class Message
{
    public string Id { get; set; }
    public string Text { get; set; }
}


public class SuccededMessage : Message
{
}

```

Generated typescript file
```
export interface SuccededMessage extends Message
{
}
```

eslint complains with _"An interface declaring no members is equivalent to its supertype .eslint[@typescript-eslint/no-empty-interface]"_.

I need both classes for clarity and avoid redundancy.

How can I write "// eslint-disable-next-line @typescript-eslint/no-empty-interface" on top of the file to deactivate the error?

Thank you!

**Comment by smkanadl** [comment]
As alternative idea: Instead of inserting ts/eslint suppressions into the typings file, you could simply exclude all typings from the linting process in the linter config.

**Comment by obriankevin11** [comment]
Thanks for the suggestion. I wanted to ignore only one rule tho'

I added this to _.eslintrc.js_, restarted eslint and it works ok
```
overrides: [
    {
      files: ['<path to the ts file generated>'],
      rules: {
        '@typescript-eslint/no-empty-interface': 'off',
      },
    },
  ],
```

**Comment by smkanadl** [comment]
@obriankevin11 ignoring a single rule is as easy as ignoring all rules. Glad I could help :-)
