### ISSUE TITLE
Type resolvation warning RT0003: Could not find suitable TypeScript type for System.DateTime. 'any' assumed.

### ISSUE THREAD

**Issue by mulgurul** [reinforced/Reinforced.Typings#26]
Sorry just disregard this Issue, it was a mistake from my side. I'm very new to Typescript and thought it had a DateTime type, but not. By mistake i was looking at wrong documentation.

I see now that there is no datetime type so any must be the resolved type.

I cant seem to delete the issue.

BR and thanks for a great and helpfull tool.

Peter Meldgaard

**Comment by pavel-b-novikov** [comment]
Please close resolved issues by yourself in further

**Comment by mulgurul** [comment]
I will, thanks a lot.

//Peter
