### ISSUE TITLE
feat: Net8 support

### ISSUE THREAD

**Issue by JohnCampionJr** [reinforced/Reinforced.Typings#264]
I know net8.0 is currently in preview status, but it'd be nice if RT would go ahead and support it since its a pretty straightforward change.

**Comment by lukedukeus** [comment]
+1, opened PR: #265

**Comment by KennethHoff** [comment]
I just came to this repo to do just this; Prematurely mention this should be updated.

**Comment by maberalc** [comment]
I see this PR is merged, but there is no new version since 6 months ago. I guess it will be updated just when .NET 8 releases, but i could be released as preview too. Anyway, how could I try to compile and use it on my tests on .NET 8?

**Comment by KennethHoff** [comment]
@pavel-b-novikov Would be nice if you could release a new version so we can test! 👍

**Comment by maberalc** [comment]
No news on the preview? Or just wait for final .NET 8 release?

**Comment by iotalambda** [comment]
I needed this for my .NET 8 project today, so I built the nuget myself and added it to a feed within my project https://github.com/iotalambda/Reinforced.Typings :/

**Comment by lindsve** [comment]
Any chance for an updated package now that .NET is officially released?

**Comment by pavel-b-novikov** [comment]
Yes. I took decision not to issue updates for all the previews. Otherwise I'd have to quit job and publish package every week :)

**Comment by Redlab1** [comment]
Hi @pavel-b-novikov, do you have an ETA on when you'll be releasing the new version?

**Comment by jeremy-allocate** [comment]
Hello!  Dotnet 8 has been officially released and the lack of a corresponding update here is blocking our upgrade.  Is there an ETA on a new release here @pavel-b-novikov?

**Comment by pavel-b-novikov** [comment]
Will handle within a week

**Comment by jeremy-allocate** [comment]
> Could you make this more bulletproof for new .net versions? When a new .net version comes out, this shouldnt be blocking us from updating our solutions.
> 
> We're considering merging away from this package due to this reason. Many packages work seemlessly for all .NET5+ versions, what makes this package not compatible with newer .NET versions?

Here was the commit from back in August that added dotnet 8 support: https://github.com/reinforced/Reinforced.Typings/commit/c9e98575f0b27fe91f31e297bb1bc2ff4078c0e0

**Comment by Redlab1** [comment]
@jeremy-allocate Yeah I know, but why is it hardcoding the .net versions that it's supporting? Also, why doest it take so long to make a new release when the only difference is some new hardcoded values? It should take 1 minute to create a new release with those changes.

**Comment by smkanadl** [comment]
@Redlab1 I can understand the frustration here, but please bear in mind that this piece of (very) valuable software is free for you to use and maintained by @pavel-b-novikov in his spare/free time.

I've had a very quick look into this topic last year and I think the reason is the rtcli tool that is loaded and executed by the dotnet cli / msbuild. And differences in the framework have caused me some trouble with dependency resolution.

**Comment by JohnCampionJr** [comment]
Might also be less maintenance if the older deprecated versions of .NET were removed.  Make this a breaking v2.0 and only support NET6.0, NET8.0, NETSTANDARD2.0

**Comment by smkanadl** [comment]
@JohnCampionJr that would (for me) make only sense if I could still target a net7.0 application. But I am not sure if that is technically possible (without rewriting the whole msbuild integration.

**Comment by JohnCampionJr** [comment]
> @JohnCampionJr that would (for me) make only sense if I could still target a net7.0 application. But I am not sure if that is technically possible (without rewriting the whole msbuild integration.

Yeah, I forgot 7.0 is still under official support until May 2024.  So it should stay; but its ultimately up to @pavel-b-novikov not me :)

**Comment by pavel-b-novikov** [comment]
I prefer not to remove any of supported .net platforms to avoid breaking changes for people who depend on RT, but use legacy .net stack. For me it costs 0, but for end users it may cost significantly more

**Comment by pavel-b-novikov** [comment]
> @jeremy-allocate why doest it take so long to make a new release when the only difference is some new hardcoded values?

Because if context switches. RT is not my full-time and not my 1st priority unfortunately

**Comment by jeremy-allocate** [comment]
Renovate just informed me that v1.6.3 has been posted and is available via [nuget](https://www.nuget.org/packages/Reinforced.Typings/).  Tested on my dotnet 8 branch and things look good, thanks @pavel-b-novikov!

**Comment by JohnCampionJr** [comment]
Thank you @pavel-b-novikov !!

**Comment by pavel-b-novikov** [comment]
You are welcome. Sorry for delay

**Comment by Redlab1** [comment]
Thank you @pavel-b-novikov, appreciate your efforts. 🥇
