### ISSUE TITLE
<RtDisable> and <TreatWarningsAsError> not working

### ISSUE THREAD

**Issue by KennethHoff** [reinforced/Reinforced.Typings#266]
Hey, I just tried to test my solution in .Net 8 to see if it there were any changed needed, and since RT isn't updated to .Net 8 yet I figured I could just disable it, but when I do, the application no longer starts due to a warning-treated-as-error.

Normally, this isn't that big of a deal as you can easily disable specific errors, but for some reason this error has no code:
![image](https://github.com/reinforced/Reinforced.Typings/assets/17124533/78a0f1e6-4a55-4eb3-b043-74373b2c18b0)

That brings 2 questions:
1. Why is that a Warning? Surely this should be information.
2. Why does it not have an error code so one can disable it.

I can work around this by disabling TreatWarningsAsError, but this is a bad experience.

**Comment by DaveSkender** [comment]
I agree here.  My use case is more about not wanting to mutate my source code on my build server (scary and volatile), but still want to be conservative with treating warnings as errors.  The way it's setup now, will always fail my build with an `Error` while treating warnings as errors and disabling RT.  I'd recommend decoupling these by removing this code: https://github.com/reinforced/Reinforced.Typings/blob/c5aadb47fd252fe0f17036c9bf08342d90b79789/stuff/Reinforced.Typings.targets#L36-L39

Related to #235
