### ISSUE TITLE
Add a custom property to a class

### ISSUE THREAD

**Issue by dariusz-wozniak** [reinforced/Reinforced.Typings#274]
Is there any way to add a custom property to an existing class (or interface)? By custom, I mean one that is not declared in the C# code.

Simple example:

```csharp
public class _ { }
```

RT declaration:

```csharp
builder.ExportAsClasses(new [] { typeof(_) }, options =>
{
    options.WithProperty("NewProperty", p => p.Type<string>());
});
```

This yields a build error:

>  Exception thrown when applying fluent configuration method for type '_': Could not locate property NewProperty in class _

**Comment by mikhail-syvachenko-syzygy** [comment]
Great idea! Have been looking for something like this for long time!

**Comment by smkanadl** [comment]
I use to implement things like this in a custom generator. For most cases you can inherit `InterfaceCodeGenerator` and override `GenerateNode`.

```
public class NewPropertyCodeGenerator : InterfaceCodeGenerator
{
    public override RtInterface GenerateNode(Type element, RtInterface result, TypeResolver resolver)
    {
        var r = base.GenerateNode(element, result, resolver);

        result.Members.Add(new RtField()
        {
            AccessModifier = AccessModifier.Public,
            IsStatic = false,
            Type = new RtSimpleTypeName("string"),
            Identifier = new RtIdentifier("NewProperty"),
            Order = -100,
        });

        return r;
    }
}

```

Then it is only a matter of use the `WithCodeGenerator` method on the fluent configuration builder.

```
builder.ExportAsInterfaces(
    types,
    conf => conf
        .WithPublicProperties(TypeInference.HandleProperties)
        .WithCodeGenerator<NewPropertyCodeGenerator>()
    );

```

**Comment by pavel-b-novikov** [comment]
Seems that I have to give more control over blueprints to my target audience...

**Comment by dariusz-wozniak** [comment]
Works like a charm, thank you for the solution, @smkanadl! 🙏
