### ISSUE TITLE
feat: Net9 support

### ISSUE THREAD

**Issue by pavel-b-novikov** [reinforced/Reinforced.Typings#276]
I create this in advance

**Comment by benpsnyder** [comment]
Can we get this published to NuGet or is there something else that needs to be done first?

**Comment by ArmandRedgate** [comment]
[.NET 9 officially released today](https://devblogs.microsoft.com/dotnet/announcing-dotnet-9/), as @benpsnyder said it would be good for a release to be done so we get the already merged changes, unless there are any blockers 🙂.

**Comment by joewashear007** [comment]
This would be awesome it could get published. this is our main blocker from upgrading our app to net9.

**Comment by pavel-b-novikov** [comment]
Pushed

**Comment by benpsnyder** [comment]
> Pushed

Thank you!

**Comment by smkanadl** [comment]
@pavel-b-novikov There is an issue in the package. The tools folder is missing the `net9.0` artifacts.

![image](https://github.com/user-attachments/assets/b1f15770-7638-457e-891f-d5df02d82a93)

Hence the package does not work. See also #283

**Comment by pavel-b-novikov** [comment]
Ay caramba!
