### ISSUE TITLE
.NET9, Windows 8.0 project - Reinforced.Typings - Could not load file or assembly 'System.Runtime, Version=9.0.0.0

### ISSUE THREAD

**Issue by BillDuffy** [reinforced/Reinforced.Typings#285]
**Following is a one-package project that demonstrates this error.**

**Here is the error message :**
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	RT0999	Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.	Reinforced	F:\p-bill.duffy\source\experimental\Reinforced\Reinforced.Typings	1	
```

**Here is an example VS2022 project that demonstrates this issue:**
![Picture1](https://github.com/user-attachments/assets/8d0ba6dd-4a0d-4357-8f06-a833223e9ec1)

**Reinforced.csproj:**
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Reinforced.Typings" Version="1.6.5" />
  </ItemGroup>
</Project>`

**Comment by smkanadl** [comment]
@BillDuffy 

Your issue is this line:
`<RtForceTargetFramework>net8.0</RtForceTargetFramework>`

You are forcing msbuild to use the net8.0 version of the RT CLI. This options is only (to my knowledge) the last resort. Usually RT will deduce the correct framework for the RT cli to load.

**Comment by BillDuffy** [comment]
Found the issue, changed this line. Sometimes the obvious... mumble, mumble...

`    <RtForceTargetFramework>net8.0</RtForceTargetFramework>`

to

`    <RtForceTargetFramework>net9.0</RtForceTargetFramework>`
