### ISSUE TITLE
Update to 1.6.4 breaks something for reinforced.typings\1.6.4\tools\net8.0\rtcli.dll

### ISSUE THREAD

**Issue by rjk-condor** [reinforced/Reinforced.Typings#287]
After updating from 1.6.3 to 1.6.4 the projekt does not build anymore with the errror
`C:\Program Files\dotnet\dotnet.exe "C:\Users\XXX\.nuget\packages\reinforced.typings\1.6.5\tools\net8.0\rtcli.dll" profile "C:\Users\XXX\AppData\Local\Temp\tmp2u4wsc.tmp"`
`5>Reinforced.Typings: Error RT0999 Unexpected: Unable to load one or more of the requested types.`

When looking into the `tmp2u4wsc.tmp` I could only find the line
`C:\Users\t2000345\.nuget\packages\reinforced.typings\1.6.4\lib\net8.0\Reinforced.Typings.dll`

Is there something missing?

**Comment by smkanadl** [comment]
I think without a (minimal) `csproj` file it'll be hard to tell.

**Comment by rjk-condor** [comment]
The used csproj looks like this:

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>10</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Reinforced.Typings" Version="1.6.5" />
    </ItemGroup>

</Project>

**Comment by smkanadl** [comment]
@rjk-condor That looks reasonable. Do you have any `<RtForceTargetFramework>` settings in your Reinforced.Typings.settings.xml?

**Comment by rjk-condor** [comment]
No, it's a comment
```c#
<!-- <RtForceTargetFramework>netcoreapp2.2</RtForceTargetFramework>	-->
``` 
Maybe this is the issue?

**Comment by smkanadl** [comment]
No, this is usually just a "last resort" options.

Do you have any `<RtAdditionalAssembly>` nodes`?

**Comment by rjk-condor** [comment]
Yes. 
I also enabled "diagnostic" log output and it gave me
```c#
8>Reinforced.Typings: Error RT0999 Unexpected: Unable to load one or more of the requested types.
Could not load file or assembly 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Das System kann die angegebene Datei nicht finden.
Could not load file or assembly 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Das System kann die angegebene Datei nicht finden.
Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=9.0.0.0, Culture=neutral, 
``` 
The update of System.Text.Json from 8.0.5 to 9.0.0 was part of the upgrade of the RtAdditionalAssembly.
I will try to downgrade this one and see if the error still exists.

**Comment by rjk-condor** [comment]
OK, so for now I will downgrade the v 9.0 assemblies back to 8.x and leave it until we can go all the way up to .NET9
Tanks for the Help
