### ISSUE TITLE
Inspecting attributes from JSON.NET [JsonObject]

### ISSUE THREAD

**Issue by PandaWood** [reinforced/Reinforced.Typings#29]
Hi, I just wanted your advice on whether I should create a new project or modify this one.

I'm thinking about using this project code-base to detect Json.NET attributes that we already have on our C# code for deserializing objects into JSON - as well.

So, my idea is to have a configuration option to look for [JsonObject] and [JsonProperty] etc as well as [TsInterface] and [TsProperty]. 

Because, many of our [TsInterface] attributes are just duplicating the attributes we have already setup using [JsonObject]

But I'm interested in your opinion... do you think this idea would be better as a separate project or as some kind of config/option in this one?

**Comment by pavel-b-novikov** [comment]
To be honest, I dont completely understand why do you need some special attributes for Json.NET? As for me, I do not use any attributes on my models when using Json.NET. Except really rare cases like [ExtensionData], or [JsonPropery] with "NullValueHandling" or overriding property name (really rare). 
So it depends on which attributes are you using and what you exactly needed.

**Comment by pavel-b-novikov** [comment]
Anyway, my suggestion will be not to rewrite RT using it as base project, but make set of extensions, based on fluent configuration. 
You might to know about [fluent configuration](https://github.com/reinforced/Reinforced.Typings/wiki/Fluent-configuration), eh?
So you can make extension that will automatically call ```.ExportAsInterfaces``` supplying all the classes in assembly having [JsonObject] attributes as first parameter and necessary configuration as second parameter. And this extension could be moved to separate assembly referencing RT.

**Comment by PandaWood** [comment]
Thanks. If you are just using JSON for DTO's, it's easy to do without special attributes in Json.NET.
But for more complex classes/models that involve logic etc, it's common to have properties that are used in C# logic but that are not used in javascript at all. That's why we need them. Many of our classes have **[JsonObject(MemberSerialization.OptIn)]** and we select only what properties are actually needed or use **[JsonIgnore]**. 

An example in front of me, is a simple class with 4 basic properties plus a property of type "User" class. "User" is a class in our domain model which has 5 lists hanging off it and about 15 properties. If we did not use [JsonIgnore] on the "User" property in this case, the bandwidth waste and even security issues, would be horrendous.

**Comment by pavel-b-novikov** [comment]
Sidenote: do not use domain entities as ViewModels :) 
Ok, in this case you can still use approach with fluent configuration that I've mentioned above. It is significantly more flexible.

**Comment by PandaWood** [comment]
Thanks, I'll look into doing that
