### ISSUE TITLE
Generate class from enum

### ISSUE THREAD

**Issue by adogg** [reinforced/Reinforced.Typings#3]
Hi,

Is it possible to generate class from enum without creating specific Code Generator?
I have an c# enum of this kind:
`
public enum MyEnum
{
    [EnumMember(Value = "Value1")] Member1,
    [EnumMember(Value = "Value2")] Member2,
    [EnumMember(Value = "Value3")] Member3,
}`
I want to have something like this in TypeScript:
`
export class MyClass {
    Member1 = "Value1";
    Member2 = "Value2";
    Member3 = "Value3";
}
`

**Comment by pavel-b-novikov** [comment]
Unfortunately, it is not posible without custom code generator. 
Try this:

```c#
public class ClassEnumCodeGenerator : TsCodeGeneratorBase<Type, RtClass>
{
    public override RtClass GenerateNode(Type element, RtClass node, TypeResolver resolver)
    {
        node = new RtClass() { Name = element.GetName() };
        foreach (var vField in element.GetFields())
        {
            var attr = vField.GetCustomAttribute(typeof(EnumMemberAttribute)) 
                        as EnumMemberAttribute;
            if (attr != null)
            {
                // here we are using RtRaw since RtField does not have initializer in AST
                node.Members.Add(
                        new RtRaw(String.Format("{0} = \"{1}\";", vField.Name, attr.Value))
                );
            }
        }

        return node;
    }
}

public class EnumMemberAttribute : Attribute
{
    public string Value { get; set; }
}

[TsClassEnum]
public enum MyCoolEnum
{
    [EnumMember(Value = "Value1")]
    One,
    [EnumMember(Value = "Value1")]
    Two,
    [EnumMember(Value = "Value1")]
    Three
}

public class TsClassEnumAttribute : TsEnumAttribute
{
    public TsClassEnumAttribute()
    {
        CodeGeneratorType = typeof (ClassEnumCodeGenerator);
    }
}
```

**Comment by pavel-b-novikov** [comment]
I've duplicated this code to [gist](https://gist.github.com/pavel-b-novikov/d4aecc28ec7f3a5e926a)

**Comment by adogg** [comment]
@pavel-b-novikov , thanks, I'll try it tomorrow. I guess if I use fluent configuration then I have to use WithCodeGenerator method?

**Comment by adogg** [comment]
@pavel-b-novikov , thanks, I'll try it tomorrow. I guess if I use fluent configuration then I have to use WithCodeGenerator method?

**Comment by pavel-b-novikov** [comment]
Yes. 
There is unfinished (but with generation working :) sample [here](https://github.com/reinforced/Reinforced.Typings/blob/master/Samples/Difficult/Reinforced.Typings.Samples.Difficult.CodeGenerators/ReinforcedTypings/Configuration.cs). You can refer to it to see how to use .WithCodeGenerator.

**Comment by adogg** [comment]
Hi there. It took me much longer as expected to try this code. Works fine, but it seems like OverrideNamespace() method doesn't work with code generator.

I use this configuration:
builder.ExportAsClass<MyNameSpace.MyEnum>()
            .ExportTo("myEnum.ts")
            .OverrideNamespace("NewNameSpace")
            .WithCodeGenerator<ClassEnumCodeGenerator>();

So, it puts generated class into original "MyNameSpace" module rather than into "NewNameSpace" module.
