### ISSUE TITLE
Feature request: Ability to set indentation type

### ISSUE THREAD

**Issue by jonsa** [reinforced/Reinforced.Typings#30]
As it it now the generated file is generated with tab indentation. I would like to be able to change this to be spaces instead.

**Comment by pavel-b-novikov** [comment]
And how much spaces do you want per tab? :)

**Comment by jonsa** [comment]
4 if it was up to me. :)
But if it was configurable from the xml it'd be more generic. I could imagine some projects might prefer 2 spaces as well.

**Comment by pavel-b-novikov** [comment]
Implemented in 1.30 branch. Please check out and run your test

**Comment by pavel-b-novikov** [comment]
Fixed in 1.3.0
