### ISSUE TITLE
[TsClass] attribute does not apply 'ForceNullable = true'

### ISSUE THREAD

**Issue by PandaWood** [reinforced/Reinforced.Typings#32]
Hi, I believe this should work, given the documentation?

That is, if I adorn my C# class with `[TsClass] `and set the attribute `[TsProperty(ForceNullable = true)]` - it should generate the TypeScript nullable "?" syntax

I believe it's due to this line of code in PropertyCodeGenerator.cs ?: 
`   if (tp.ForceNullable && element.DeclaringType.IsExportingAsInterface() && !Context.SpecialCase)`

Which seems to limit the ForceNullable generation to interfaces (TsInterface)

**Comment by pavel-b-novikov** [comment]
Correct. Will be fixed in next release

**Comment by pavel-b-novikov** [comment]
Fixed in 1.30 branch. 
You can check it out, run test and close issue. Soon or later I will merge it to master

**Comment by pavel-b-novikov** [comment]
Fixed in 1.3.0
