### ISSUE TITLE
1.3.0 release date?

### ISSUE THREAD

**Issue by urbanmichal** [reinforced/Reinforced.Typings#33]
Hi guys,

When do you plan to release 1.3.0 version?

**Comment by pavel-b-novikov** [comment]
Approx. 2nd week of march

**Comment by urbanmichal** [comment]
Thank you very much.
Serdecznie pozdrawiam,
Michał Urban | +48 665 990 004 | urban.michal@icloud.com

W dniu 24 lut 2017 o godz. 11:46 użytkownik Pavel Novikov <notifications@github.com> napisał(a):

Approx. 2nd week of march
