### ISSUE TITLE
How can I debug my code in Configure method?

### ISSUE THREAD

**Issue by urbanmichal** [reinforced/Reinforced.Typings#35]
Hi,

I would like to add breakpoint in some line in Configure method. How could I debug it?

**Comment by pavel1269** [comment]
You can use System.Diagnostics.Debugger.Launch()

**Comment by pavel-b-novikov** [comment]
Sorry, didnt noticed your question. 
You can use Console.WriteLine within configure method and examine msbuild's logs. To elevate velocity of MSBuild's output go to Tools - Options - Projects And Solutions - Build and Run - there will be 2 dropdowns with verbosity levels. You need to select Detailed. After that you will see all the Console.WriteLine output in your VS's Output window. 
OR you can add path to your MSBuild.exe to your PATH env. variable and build your .csproj from command line using ```msbuild.exe MyProject.csproj /v:d > buildlog.txt". Then you can examine buildlog.txt file for error and outputs. 

Another option is to run RT exporting process from outside of console tool. To do that, you can write code that is pretty similar to code from [bootstrapper](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Cli/Bootstrapper.cs). I have created [small gist](https://gist.github.com/pavel-b-novikov/1285b623aba37307a855385b4144ceac) to illustrate it.

**Comment by urbanmichal** [comment]
Hi, great, that's the info I needed. Good job guys, thank you :-) 👍
