### ISSUE TITLE
ExportAsClasses isn't genererating classes for parents or types for properties.

### ISSUE THREAD

**Issue by sztrzask** [reinforced/Reinforced.Typings#38]
Example. Given

```c#
public abstract  class A
{
    public B SomeProperty {get;set;}
}

public class C : A
{
}
```

I'd expect `ExportAsClasses(new []{typeof(C)}) ` to generate classes for B, A and then C. Instead I got only class C without any properties.

**Comment by pavel-b-novikov** [comment]
RT preserves inheritance, so you should explicitly export all 3 classes - it will product correct inheritance hierarchy.

**Comment by pavel-b-novikov** [comment]
As workaround, you could create extension method for Type that will extract all related types and wrap them into array. Then you can pass this array to .ExportAsClasses
