### ISSUE TITLE
Too many references causes rtcli.exe to fail due to > 32000 characters in command line arguments

### ISSUE THREAD

**Issue by JustASquid** [reinforced/Reinforced.Typings#40]
[EDIT] After further investigation, I found that the culprit is the References parameter in Reinforced.Typings.Targets. When a project has a lot of references, the exe cannot be invoked as the argument becomes too long for Windows to handle (ugh). 

If I try changing the code to give a smaller number of References, I get errors that certain assemblies cannot be loaded. Is there a way for the program to infer the references? It seems crazy that all the project's references need to be passed in like this. 

I'm happy to work on a fix but I'm not sure what form that fix would take.

[ORIGINAL POST]
When I try to build the project after freshly installing Reinforced.Typings, I get the following error:

`The specified task executable "rtcli.exe" could not be run. The filename or extension is too long	`

I checked, and the full path to `rtcli.exe` is only ~70 characters long.

Any idea what could be causing this issue?

**Comment by pavel-b-novikov** [comment]
Interesting. Can we contact via skype or some other environment? I need to see your project.

**Comment by JustASquid** [comment]
Hey, thanks for your response! Yeah, you can contact me on Skype, username
danie1.west

**Comment by JustASquid** [comment]
Fixed in upcoming build, thanks Pavel
