### ISSUE TITLE
Is it possible to export enum as `export const enum MyEnum` ?

### ISSUE THREAD

**Issue by rluiten** [reinforced/Reinforced.Typings#41]
I am having trouble defining some configurations based on an enum.
typescript@2.4.2
awesome-typescript-loader@3.2.1
webpack@2.7.0

eg.
In file MyEnum.ts produced by Reinforced Typings
```typescript
module Vm {
  export enum MyEnum {
    Created = 0,
    Waiting = 1
  }
}
```

In file MyConfig
```typescript
export const MyConfig = {
  [Vm.MyEnum.Created]: {
     shortMessage: 'Created',
     longMessage: 'A much longer explanatory message'
  }
  /* etc */
}
```

Without the 'const' typescript is leaving the value `MyEnum.Created` in the output object and run time crash.

I found some info about how adding `const` to the enum causes the compiler to replace the identifier with the integer, which would at least get this working... [code base came from from typescript 1.8]

It is quite possible I am just being naive and have done it the hard way, I would appreciate a pointer in the right direction if that is the case.

**Comment by pavel-b-novikov** [comment]
Hm. Currently this feature is not supported. I'm busy with another work to do. Can you please provide more details about how do you see this feature in RT?

**Comment by rluiten** [comment]
How I would use it is the second source example above repeated here.
Define a set of Config objects one for each enum member as follows.
Then where i need the config i can   use  `MyConfig[myConfigValue];`

```typescript
export const MyConfig = {
  [Vm.MyEnum.Created]: {
     shortMessage: 'Created',
     longMessage: 'A much longer explanatory message'
  }
  /* etc */
}
```

If the export is 'export const enum MyEnum' it just works, as the in the numeric value of `Vm.MyEnum.Created` is substitued. The `const enum` from the reading I have done makes enums gets converted to there numeric values as encountered so leaves no overhead of a enum concept left behind.

There doesn't seem to be any sort of search/replace filter I might be able to apply as part of the export process that might let me override the output without a feature in the Reinforced Types itself.

I have worked around it at the moment by creating a function as follows to return what I need.
```typescript
getMyConfig(Vm.MyEnum value) {
  switch( value) {
    case Vm.MyEnum.Created: return  {
     shortMessage: 'Created',
     longMessage: 'A much longer explanatory message'
  };
  }
} 
```

I don't need `const enum` export at the moment as the code is not performance sensitive, but I can see real value in some cases supporting the const version.
Cheers, Thanks for the useful tool btw.

**Comment by pavel-b-novikov** [comment]
So is it usable for enums only?

**Comment by rluiten** [comment]
I am only aware of the const keyword used with enum changing the behavior of typescript at the moment,  I am not an expert.

**Comment by rluiten** [comment]
Ok, just discovered my previous work around to create a function did not work.
It appears I don't understand how typescript lets me use non `const enum` member identifiers, the output JS keeps the fully qualified name to the enum, which fails.

I currently can't import the module by name as it does not have an export statement.
If i modify the output of Reinforced Typings to prefix the module with `export` I can then import the module by name and things appear to work correctly. So its the difference between enums in typescript as purely converted to there value (using const), and enums as part of typescript module system and then need to be imported.

Either way they work then. 

All this issue is purely my previous experience with typescript 1.8 where they were only ephemeral in nature it appears.

Is it possible without modifying reinforced typings to get export on the module name ?
Sorry about the volume of messages, this has been quite a learning exercise for me.

**Comment by rluiten** [comment]
I had a quick look at the project, to see if i might be able to add an option for either const enum output or export module, but I got very lost in 1/2 an hour.

**Comment by pavel-b-novikov** [comment]
Requested functionality now supported in 1.3.3
[Check out your unit test](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.RluitenConstEnums.cs)

**Comment by rluiten** [comment]
Cool, will check it out soon.
