### ISSUE TITLE
Type guards

### ISSUE THREAD

**Issue by Ithalica** [reinforced/Reinforced.Typings#42]
Is it possible to write C# code to generate TypeScript type guards?

My case if the following:

	export interface IBaseClass
	{
		Id: number;
		Name: string;
	}
	export interface IFirstClass extends IBaseClass
	{
		SomeProperty: number;
	}
	export interface ISecondClass extends IBaseClass
	{
                SomeOtherProperty: string;
	}

and wanting to use it in a method like 

        doStuff(value: IBaseClass): void
        {
                if (value is IFirstClass) {
                        //Do something with value.SomeProperty 
                }
        }

I know that in order to do this, I need some type guarding code like this:

    export function isFirstClass(item: IFirstClass | ISecondClass): item is IFirstClass {
        return (<IFirstClass>item).SomeProperty !== undefined;
    }

Writing it, is not a big deal as such, but I wanted to know if there are any built in options to generate this so I don't have to maintain it manually when the file is updated?

**Comment by pavel-b-novikov** [comment]
Currently this feature is not suppoerted

**Comment by pavel-b-novikov** [comment]
Well, I have re-read your request and can suggest to use such tools as [Substitutions and inline type inferers](https://github.com/reinforced/Reinforced.Typings/wiki/Types-Resolution#substitutions)
