### ISSUE TITLE
DateTime? not supported?

### ISSUE THREAD

**Issue by bigdnf** [reinforced/Reinforced.Typings#43]
I'm trying to generate typescript with Reinforced.Typings and I have a problem with DateTime? type. In build output I have an info that Type resolution failed with code RT0003. I could use builder.Substitute for choose type manually but I think that this type should be resolved automaticly?

**Comment by pavel-b-novikov** [comment]
Hi! Problem is not in ```DateTime?``` type, so .Substitute wont help. The problem is that RT sees that you have nullable value-type and automatically makes property nullable. So currently this problem cannot be solved.

**Comment by pavel-b-novikov** [comment]
.ForceNullable now supports disabling nullability
[Test And Example](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.NewForceNullable.cs)
