### ISSUE TITLE
Tsconfig

### ISSUE THREAD

**Issue by Kuarn** [reinforced/Reinforced.Typings#46]
I have an issue after including reinforced typings, that all my typescript get's compiled in their folder instead of what is specified in the tsconfig.json, 

Hopefully, you can point out an error I might have made.

Reinforced.typings.settings.xml:
![image](https://user-images.githubusercontent.com/14737548/29863254-611f0c06-8d6f-11e7-93e9-f653df36d046.png)

end of csproj:
![image](https://user-images.githubusercontent.com/14737548/29863303-8899d9d2-8d6f-11e7-8dc7-c908696b24d9.png)

If I put the import project for reinforced typings above, it won't run at all.

tsconfig:
![image](https://user-images.githubusercontent.com/14737548/29863324-9da6b430-8d6f-11e7-94f6-be4e1f92fcdc.png)

**Comment by pavel-b-novikov** [comment]
Try setting RtBypassTypescriptCompilation to ```true```

**Comment by Kuarn** [comment]
Was apparantly using an older version, works fine after I updated to the newest. Thanks for the reply though
