### ISSUE TITLE
Support ValueTuple

### ISSUE THREAD

**Issue by chris-cartwright** [reinforced/Reinforced.Typings#47]
Reinforced.Typings.TypeExtensions.IsTuple doesn't check for System.ValueTuple and returns false, causing all ValueTuples to map to any. Can support for ValueTuple be added?

**Comment by pavel-b-novikov** [comment]
Will be added in further release

**Comment by chris-cartwright** [comment]
It would also be nice if Reinforced.Typings used the `ValueTuple`'s item names to generate an object instead of using TypeScript's tuples. Some quick searching found `TupleElementNamesAttribute`: https://stackoverflow.com/a/43489034

**Comment by pavel-b-novikov** [comment]
Please implement feature above by yourself using [inline type inferers or substitutions](https://github.com/reinforced/Reinforced.Typings/wiki/Types-Resolution#substitutions). By default RT will convert ```ValueTuple``` to TS tuple.
