### ISSUE TITLE
Support for .NET Core v1/v2 (netcoreapp1.1 / 2.0)?

### ISSUE THREAD

**Issue by AKlaus** [reinforced/Reinforced.Typings#48]
It seems that `.NET Core` is unsupported. 
However, it allowed to install the NuGet package (not specified framework versions in the `.nuspec` files?) for a `netcoreapp1.1` project, but any references to the classes can't be resolved.

Should we expect .NET Core support of the project?

**Comment by pavel-b-novikov** [comment]
Yes, it will appear soon, but anyway it will NOT support ```project.json```

**Comment by nohwnd** [comment]
@pavel-b-novikov How soon is "soon" please? :)

**Comment by PandaWood** [comment]
If I ever need to ask "how soon", I would check the code out and start seeing what I can do to help

**Comment by pavel-b-novikov** [comment]
@nohwnd I will try to contribute this weekend. Sorry, I have too much work to be done

**Comment by nohwnd** [comment]
Thanks, I tried porting it but had no luck making it work. The code compiled, but the generation did not run. Probably because I could not reuse your nuget structure and the msbuild settings.

**Comment by pavel-b-novikov** [comment]
@nohwnd can you share your branch or make pull request?

**Comment by nohwnd** [comment]
@pavel-b-novikov There were no changes actually, I just moved all the projects to `netstandard2.0` and build them as nuget packages. I can have another closer look tomorrow. Maybe I can fix it. If I can I will definitely post PR.

**Comment by pavel-b-novikov** [comment]
@nohwnd Actually I'm worried about one and only thing. RT opens .dlls using LoadLibrary. I'm not sure that 4.6-version of RT will open .net core .dlls. And I have no idea how it will work with netstandard2.0 assemblies. 
![c0e1502ceba1e2dbedf7aa1f274d8ca9cdb71296](https://user-images.githubusercontent.com/2521412/32358493-1dde3bb4-c079-11e7-951d-cb78768ad9c8.gif)

**Comment by nohwnd** [comment]
@pavel-b-novikov what .net versions we need to keep compatibility with? I saw you are using .NET 4.5 at the moment. Also if I understand how it works: you hook into the build and run your rtcli.exe to generate the typings. In core there are two “profiles” netstandard2.0 and netcoreapp2.0. ASP.NET apps and console apps are using netcoreapp2.0 and can reference netstandard2.0 libraries, but ot does not work the other way. Reflection is available in netcoreapp2.0, so hopefully the loading will work. On ASP.NET Core 1.0 there is netcoreapp1.0 profile (for web apps and consoleapps) which is based on netstandard1.6 which also has reflection. The distribution will probably be difficult, but there are few packages I saw that support all of those runtimes, so there is probably a way to do it.

**Comment by nohwnd** [comment]
@pavel-b-novikov is there any documentation on how you build the final nuget package? I see there is `build.msbuild` file calls `nuget.exe` but I'd like to know how you do it exactly, please.

**Comment by pavel-b-novikov** [comment]
basically to call ```msbuild build.msbuild``` is enough. but do not destroy contents of "package" folder

**Comment by nohwnd** [comment]
@pavel-b-novikov yup figured that out, now I am having trouble running the rtcli as part of the build, it fails on me because it misses dependencies. Why do we need external executable? We are invoking it from C# code that from the integrate library, so couldn't we just generate the typings directly without invoking a new process?

**Comment by pavel-b-novikov** [comment]
@nohwnd Because some people use rtcli.exe without integration into msbuild. E.g. as separate build step, invoked with different parameters.

**Comment by nohwnd** [comment]
@pavel-b-novikov I merged all the projects together and build proper package from it that builds for netcoreapp2.0 and net461, it works from command line with both dotnet build and dotnet msbuild, but it does not work with the msbuild.exe, I don't know why. Tried everything I could come up with but I always circle back to: 

```
Copyright (C) Microsoft Corporation. All rights reserved.

  Starting with args:
  Runnins as net 461
  SourceAssemblies="C:\projects\WebApplication5\WebApplication5\obj\Debug\netcoreapp2.0\WebApplication5.dll"
  TargetFile="C:\projects\WebApplication5\WebApplication5\\project.ts"
  TargetDirectory="C:\projects\WebApplication5\WebApplication5\Scripts\MyApplication"
  ReferencesTmpFilePath="C:\Users\nohwnd\AppData\Local\Temp\tmpC7E9.tmp"
  Hierarchy="False"
  DocumentationFilePath=""
  ConfigurationMethod="Core.ReinforcedTypingsConfiguration.Configure"
  Starting bootstrapper
Reinforced.Typings CLI generator (c) 2015 by Pavel B. Novikov
Looking up for assembly C:\projects\WebApplication5\WebApplication5\obj\Debug\netcoreapp2.0\WebApplication5.dll
Already have full path to assembly C:\projects\WebApplication5\WebApplication5\obj\Debug\netcoreapp2.0\WebApplication5.dll
Looking up for assembly System.Runtime.dll
Assembly System.Runtime.dll found at C:\Users\nohwnd\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Runtime.dll
Reinforced.Typings : Unexpected error RT0999: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at Reinforced.Typings.Cli.Bootstrapper.ResolveFluentMethod(ExportContext context)
   at Reinforced.Typings.Cli.Bootstrapper.Main(String[] args)
```

**Comment by pavel-b-novikov** [comment]
You can take look to my branch ```netcore```. There I did port to several platforms and now paused at building it

**Comment by nohwnd** [comment]
I will. Is there maybe a more direct channel where we can communicate? Twitter maybe (mine is @nohwnd)? Or skype (me@jakubjares.com)? I don't want to spam you, but it would be easier way to discuss what you have already tried, and what I have already tried.

**Comment by pavel-b-novikov** [comment]
Done. In version 1.4.0

Big thanks to @nohwnd for help and support!
