### ISSUE TITLE
How to identify what caused failed build?

### ISSUE THREAD

**Issue by adogg** [reinforced/Reinforced.Typings#5]
Do you create some kind of log or something? Because "rtcli.exe" exited with code 1." tells nothing unfortunatelly.

**Comment by pavel-b-novikov** [comment]
You can build your project from windows console using msbuild.exe specifying detailed verbosity to find out what went wrong:

```
msbuild /v:d YourProject.csproj
```

**Comment by adogg** [comment]
@pavel-b-novikov thanks. The issue is this:
I have an edge case where my C# models are inside Console Application project, basically in MyApp.exe assembly. But it seems like you're looking for an assembly with name MyApp.exe.dll. Error message is this: 

System.IO.FileNotFoundException: Could not load file or assembly 'file:///h:\Projects\MySolution\MyProject\obj\Debug\MyApp.exe.dll' or one of its dependencies. The system cannot find the file specified.
  File name: 'file:///h:\Projects\MySolution\MyProject\obj\Debug\MyApp.exe.dll'

**Comment by pavel-b-novikov** [comment]
@adogg Thanks for bug report. I will fix it as soon as I get my hands on RT. 
As temporary solution consider moving your models to separate assembly. Btw it may be good step for your application overall.

**Comment by adogg** [comment]
@pavel-b-novikov agree, but it's a pet project so I want to keep it as simple as possible.

**Comment by pavel-b-novikov** [comment]
Your requirements were implemented in version 1.2.2
Also added VS-friendly diagnostics messages
