### ISSUE TITLE
new issue policy for 1.4.0 - unable to create new "reinforced-typings" tag on SO + original Q

### ISSUE THREAD

**Issue by vmandic** [reinforced/Reinforced.Typings#54]
Sorry for this silly issue which actually leads to the real issue... but I can not tag my question on StackOverfow with "reinforced-typings" due to having less then 1500 reputation. :)

So here is the link to it: https://stackoverflow.com/questions/47220861/upgrading-reinforced-typings-to-1-4-0-from-1-3-7-crashes-build

**Comment by pavel-b-novikov** [comment]
answered there
