### ISSUE TITLE
ShouldBeCamelCased=false doesn't override config settings

### ISSUE THREAD

**Issue by PandaWood** [reinforced/Reinforced.Typings#56]
`TsProperty(ShouldBeCamelCased=false`) property only works half-way ;-)
I gather if you set it to true, then it will override the default config settings of false - this is what it claims to do but I have no need for this

But I do want it to do the opposite... and it will not

eg the below example, still outputs "originalName" camel cased - even though I've explicitly set it to *not  camel case* - where my settings are CamelCase by default
```
[TsProperty(ShouldBeCamelCased = false)]
public virtual string OriginalName { get; set; }
```

**Comment by PandaWood** [comment]
Ah, I see, I can just use 		[TsProperty(ShouldBePascalCased = true)]

**Comment by pavel-b-novikov** [comment]
Yes
