### ISSUE TITLE
"Class used before its declaration" in the generated file

### ISSUE THREAD

**Issue by yegorpetrov** [reinforced/Reinforced.Typings#58]
Basically, this:

![image](https://user-images.githubusercontent.com/10397442/34050026-3d9ff5ea-e1db-11e7-891b-8f5b18f3e0b4.png)

I'm not sure if it's a bug, but I guess it shouldn't happen at least in the default configuration.

Here is the example from the screenshot:
[reinforced_class_used_before_its_declaration.zip](https://github.com/reinforced/Reinforced.Typings/files/1563259/reinforced_class_used_before_its_declaration.zip)

**Comment by pavel-b-novikov** [comment]
Why dont you use ```.Order``` method?

**Comment by yegorpetrov** [comment]
The problem I see here is that the output is erroneus by default. And it can be cumbersome to figure out and maintain the proper order in a situation with numerous interdependent classes. I kinda expected this framework to order types properly by itself.

Is this out of the scope of the project? Were there attempts to sort it out automatically?

**Comment by pavel-b-novikov** [comment]
It is out of scope of project because 
a) this case is complex to detect and resolve when exporting to multiple files/namespaces
b) this case is extremely rare and easily fixable by pulling all the base classes to the top using ```.Order```
c) so according to previous 2 items, ratio of time spent implementing this feature/collected benefits is extremely low

So for now I'm not going to implement that. If you want to implement this feature - feel free to fork.

**Comment by yegorpetrov** [comment]
If someone else comes upon this issue, here's one way to "pull all the base classes to the top" in a more or less universal manner:

    private class InheritanceComparer : IComparer<Type>
    {
        public int Compare(Type x, Type y)
        {
            var i = default(int);
            if (y == null) return i;
            if (x.BaseType == y) i++;
            else if (y.BaseType == x) i--;
            return i + Compare(x, y.BaseType);
        }
    }
    ...
    IEnumerable<Type> dtoClasses...
    Func<Type, int> orderFunc = dtoClasses.OrderBy(t => t, new InheritanceComparer()).ToList().IndexOf;
    cfg.ExportAsClasses(dtoClasses, c => c.Order(orderFunc(c.Type))...

May be quite far from perfect, it's only tested to cover my specific case.

**Comment by pavel-b-novikov** [comment]
Thank you, Egor! But it would be much better if you post such kind of question to stackoverflow - more audience coverage there.

**Comment by vmandic** [comment]
Thanks for the idea @yegorpetrov, the proposed solution is OK but the `c.Order(orderFunc(c.Type))` call does not work as expected (I am using the latest tool version of 1.4.6), i.e. the reflected/translated code is not in the order it should be...

I made a bit more verbose version of the hierarchy enumeration with a Type dict like so:

```
    public static void Configure(ConfigurationBuilder builder)
    {
      var types = typeof(Class1).Assembly.GetTypes().ToList();

      var orderedTypes = new Dictionary<Type, List<Type>>();
      types.ForEach(t => orderedTypes.Add(t, EnumerateHierarchy(t, e => e.BaseType).Reverse().ToList()));
      builder.ExportAsClasses(types, c => c.Order(orderedTypes[c.Type].IndexOf(c.Type)));
    }

    static IEnumerable<T> EnumerateHierarchy<T>(T item, Func<T, T> selector) where T : class
    {
      do
      {
        yield return item;
        item = selector(item);
      }
      while (item != default(T));
    }
```

... I tested this separately on three class files (Class1, Class2, Class3) from three different Namespaces like so:

```
namespace ReinforcedTypings.DifferentNamespaces.Ns1
{
  public class Class1
  {
    public int AnIntegerPropNs1 { get; set; }
    public string AStringPropNs1 { get; set; }
  }
}

namespace ReinforcedTypings.DifferentNamespaces.Ns2
{
  public class Class2 : Class1
  {
    public int AnIntegerPropNs2 { get; set; }
    public string AStringPropNs2 { get; set; }
  }
}

namespace ReinforcedTypings.DifferentNamespaces.Ns3
{
  public class Class3
  {
    public int AnIntegerPropNs3 { get; set; }
    public Class1 AClass1PropNs3 { get; set; }
  }
}
```

And the tested order I get is:

- Class 3 with order number 1
- Class 2 with order number 2
- Class 1 with order number 1

So either way the Class1 should appear before Class2 which extends it in TypeScript so we shouldn't get the error of having a class used before its declaration, but unfortunately that is not the case.

The output:

![image](https://user-images.githubusercontent.com/1390895/36200308-9097ce1e-117c-11e8-8822-b18df6004221.png)

**Comment by yegorpetrov** [comment]
@vmandic I think that's because you have separate namespaces. You can't expect the lower level order to override the higher level one.

**Comment by pavel-b-novikov** [comment]
RT. Connecting people.
