### ISSUE TITLE
Assemblies are not signed

### ISSUE THREAD

**Issue by NinjaCross** [reinforced/Reinforced.Typings#59]
Both **Reinforced.Typings.dll** and **Reinforced.Typings.Integrate.dll** are distributed via NuGet as not signed assemblies.
This is a blocking problem, since it prevents usage of Reinforced Typings in any project that involves signed assemblies.

**Comment by ClaudioNist** [comment]
This is a blocking problem for all my projects

**Comment by pavel-b-novikov** [comment]
roger, will fix asap

**Comment by pavel-b-novikov** [comment]
Fixed in version 1.4.5
My apologizes for this issue, signing was removed when changing build approach necessary to create .NET core version
