### ISSUE TITLE
Nuget dlls not signed

### ISSUE THREAD

**Issue by smooluk** [reinforced/Reinforced.Typings#6]
When building a signed module that makes use of reinforced.typings, I get the following compiler error:

CSC : error CS1577: Assembly generation failed -- Referenced assembly 'Reinforced.Typings' does not have a strong name

Can you update the nuget package with a signed library?

**Comment by pavel-b-novikov** [comment]
Sure. Will do on next release

**Comment by pavel-b-novikov** [comment]
Your requirements were implemented in version 1.2.2

**Comment by madhavpatel6** [comment]
Look like version 1.4.0 is not signed
