### ISSUE TITLE
Include default values when generating properties, especially for static props

### ISSUE THREAD

**Issue by masteroleary** [reinforced/Reinforced.Typings#61]
I would like this class with static properties
```
public class Constants
{ 
    public const string APIENVIRONMENT_NONE = "NONE";  
    public const string APIENVIRONMENT_DEVELOPMENT = "DEVELOPMENT"; 
    public const string APIENVIRONMENT_PRODUCTION = "PRODUCTION";          
}
```

to generate this typescript class
```
export class Constants
{ 
    public static APIENVIRONMENT_NONE: string = "NONE";
    public static APIENVIRONMENT_DEVELOPMENT: string = "DEVELOPMENT";
    public static APIENVIRONMENT_PRODUCTION: string = "PRODUCTION"; 
}
```

Originally posted here
https://stackoverflow.com/questions/49101724/how-to-include-static-property-values-using-reinforced-typings-for-c-sharp-to-ty?noredirect=1#comment85208875_49101724

**Comment by pavel-b-novikov** [comment]
Implemented in version 1.4.7
[related unit test](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.ConstantProperties.cs)
