### ISSUE TITLE
Expose CodeGenerator's Context.Project property. 

### ISSUE THREAD

**Issue by stho01** [reinforced/Reinforced.Typings#62]
Disclaimer: I'm sorry if this is something that is supposed to be reported on Stackoverflow.. but anyways. 

After updating to `v1.4.8` I am not able to use the `GetExportedMethods()` extension method anymore. 
I noticed that the method is now located inside the Blueprint class which is a part of the Context.Project property and that the property is not accessible outside the assembly.

So here's the problem:
I'm trying to use Reinforced.Typings to export a SignalR Hub.
Every method that is exported from the SignalR should become a JQueryPromise although the method does not return a `Task` or `Task<T>`..

e.g.: `public string GetMessage() {...}` should become `getMessage(): JQueryPromise<string>`

I know that Substitution might solve some of the problems , but I'm not sure if it will solve all the methods that don't return a `Task`

The CodeGenerator (` public class SignalRHubGenerator : InterfaceCodeGenerator`) that I've wrote, overrides the ExportMethods method and wraps the RtFuncion.ReturnType in a RtSimpleTypeName("Promise"). 
```C#
protected override void ExportMethods(ITypeMember typeMember, Type element, TypeResolver resolver, IAutoexportSwitchAttribute swtch)
{
    var hubAttribute = element.GetCustomAttribute<TsSignalRHubAttribute>();
    var members = element.GetExportedMethods();

    foreach (var methodInfo in members)
    {
        if (methodInfo.IsPublic)
        {
            var member = GenerateHubMethod(methodInfo, resolver, hubAttribute);
            typeMember.Members.Add(member);
        }
    }
}

private RtFuncion GenerateHubMethod(MethodInfo methodInfo, TypeResolver resolver, TsSignalRHubAttribute hubAttribute)
{
    var generator = Context.Generators.GeneratorFor(methodInfo, Context);
    RtFuncion member = generator.Generate(methodInfo, resolver) as RtFuncion;
    
    if (IsTaskType(methodInfo.ReturnType))
        ExportTaskFunction(member, methodInfo, resolver, hubAttribute);
    else if (methodInfo.ReturnType == typeof(void))
        member.ReturnType = new RtSimpleTypeName($"{hubAttribute.PromiseTypeName}<void>");
    else
        member.ReturnType = new RtSimpleTypeName(hubAttribute.PromiseTypeName, member.ReturnType);

    return member;
}
```

By exposing the `Project` property it can solve my problem but....

It might be possible that I think about this in the most complicated way and I'm open to other suggestions to solve this problem 😄

**Comment by pavel-b-novikov** [comment]
It must be exposed? no? Damit..

**Comment by stho01** [comment]
The generic substitutions works great for all the `Task<T>` types. 
But how do I wrap none `Task` return types with a JQueryPromise<T>?

This is an example of what I want the Hub to look like after export: 

```C#
public class ChatHub : Hub {
    public void DoSomething() {...}
    public string Message() {...}
    public void DoSomethingAsync() {...}
    public Task<strin>g MessageAsync() {...}
}
```

```TypeScript
export interface ChatHub {
    doSomething(): JQueryPromise<void> {...}
    message(): JQueryPromise<string> {...}
    doSomethingAsync(): JQueryPromise<void> {...}
    messageAsync(): JQueryPromise<string> {...}
}
```

**Comment by pavel-b-novikov** [comment]
Oh, fine. Will expose it right now. 
I'm sorry, I have prepared eveything for ProjectBlueprint to make it exposed, but forgot to make property public. :(

**Comment by pavel-b-novikov** [comment]
Done. 
Please wait for package reindex
