### ISSUE TITLE
ExportAsClasses hangs build for generic types since v1.4.8

### ISSUE THREAD

**Issue by konrad147** [reinforced/Reinforced.Typings#63]
I have custom `RtConfigurationMethod` . In my configuration method I have this code:
```
builder.ExportAsClasses(new[] { typeof(Model<>) }, x => x.DontIncludeToNamespace())
```
Model class:
```
public class Model<TType>
{
}
```

For such configuration build hangs on version 1.4.8 and above. Version 1.4.7 and lower works fine.
Seems to be issue only for generic types, for ordinary types work correctly.

**Comment by pavel-b-novikov** [comment]
Fixed in version 1.4.91
[unit test](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.GenericsExport2.cs)
