### ISSUE TITLE
Error when generating interfaces contained in a .netstandard 2.0 library

### ISSUE THREAD

**Issue by dgxhubbard** [reinforced/Reinforced.Typings#64]
I have a .netstandard 2.0 library when I rebuild to generate typescript interfaces I get the exception below which causes the library to not build. I tried upgrading to 1.4.91 to get rid of the error but had no luck. I am not sure if there is something in  Reinforced.Typings  that is being searched for. 
The library that is being built is to be used in .net core 2 app I am not sure if that effects Reinforced.Typings or not. My settings file has default settings and the target file is project.ts.

Severity	Code	Description	Project	File	Line	Suppression State
Error	RT0999	Could not load type 'System.ComponentModel.Composition.ExportAttribute' from assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	GtModel	C:\Repository\GtNext\Source\Base\Next\GtModel\Reinforced.Typings	1

**Comment by pavel-b-novikov** [comment]
Hm. 
Can you redirect buggy build output to some .txt file and show it to me? It would be better to have full stack trace that RT outputs in such cases.

**Comment by dgxhubbard** [comment]
When I run msbuild on the project there is no mention of Reinforced.Typings. I have added the file MsBuildLog.txt.

[MsBuildLog.txt](https://github.com/reinforced/Reinforced.Typings/files/1856890/MsBuildLog.txt)

When I build in visual studio 2017 I see the error. I have added the file VsBuildLog.txt.

[VsBuildLog.txt](https://github.com/reinforced/Reinforced.Typings/files/1856895/VsBuildLog.txt)

**Comment by dgxhubbard** [comment]
I did some more research on this and found this information about

[GetCustomAttributes](https://stackoverflow.com/questions/12814723/what-is-an-equivalent-method-to-getcustomattributes-for-netcore-windows-8-fr?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

I saw the same error I mentioned when testing for TsInterface attribute. Below is some code to try:

`        private List<Type> GetTypesWithAttribute< T >  ( Assembly assembly ) where T : Attribute
        {
            var types = new List<Type> ();

            Type [] typesTmp = null;

            try
            {
                typesTmp = assembly.GetTypes ();

            }
            catch ( ReflectionTypeLoadException rex )
            {
                var msg = rex.Message;

            }

            if ( typesTmp != null )
            {
                foreach ( Type type in typesTmp )
                {
                    try
                    {

                        var attribute = type.GetTypeInfo ().GetCustomAttribute<T> ();
                        if ( attribute != null )
                        {
                            types.Add ( type );
                        }
                    }
                    catch ( Exception ex )
                    {
                        var msg = ex.Message;
                    }

                }
            }

            return types;
        }

`

**Comment by pavel-b-novikov** [comment]
I'm sorry that I do not have enought time to look at it right now, but in our team we've had same problem and after that I have added [following lines](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings/TypeExtensions.cs#L24) to avoid such situation. 
Unfortunately, your logs does not contain enough information - I was mistaken when instructed you how to get log via console. I forgot to ask you to rise verbosity level, so actually it must be ```msbuild YourProject.csproj /v:d > logfile.txt```. Sorry for that :( 
But issue is pretty clear overall - I just need to know *when* this happens, so I could wrap it with same try/catch for handling ReflectionException.

**Comment by pavel-b-novikov** [comment]
No response
