### ISSUE TITLE
Be able to reference external libraries in ReinforcedTypings-created types without creating invalid imports

### ISSUE THREAD

**Issue by PandaWood** [reinforced/Reinforced.Typings#70]
Some trouble we had is that we need this TypeScript typing

`export interface IMyTreeNode extends kendo.data.Node { ... }`

From a class which has to inherit from an external/3rd party library - which just means we need the string to be exactly "kendo.data.Node"

The "fake" interface technique below works and outputs the line quoted above.

```
[TsInterface(Name = "kendo.data.Node", AutoI = false)]
interface KendoDataNode { }

[TsInterface]
public class MyTreeNode: KendoDataNode { ... }
```

But this does not work when settings *UseModules* and *DiscardNamespacesWhenUsingModules* are both set to true - in that case it creates an import which doesn't compile.

`import { kendo.data.Node } from '../../kendo.data.Node';`

So we need some way of controlling the import statement - in this case, creating no import at all would work perfectly.

**Comment by pavel-b-novikov** [comment]
[ThirdParty functionality added in version 1.5](https://github.com/reinforced/Reinforced.Typings/blob/features-1.5/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.ThirdParty.cs)
