### ISSUE TITLE
Angular CLI project d.ts

### ISSUE THREAD

**Issue by marco-gallinari** [reinforced/Reinforced.Typings#73]
Hi,

I'm trying to generate d.ts files for my angular cli project this way:

[TsClass] 
[TsFile("destinationPath")]
attribute for all classes

in config xml:

`<RtDivideTypesAmongFiles>true</RtDivideTypesAmongFiles>`

server side (net core 2.0 api) builder:

```
builder.Global(x => x.UseModules(true, true)
                           .CamelCaseForProperties(true)
                           .ExportPureTypings(true)
                           .RootNamespace("Namespace")
```
 
generated d.ts files contains unnecessary import declarations, that generates error "(imported) File xxx is not a module."

If I remove import lines from generated files, the application will compile and run succesfully.

Is there a way I can force Reinforced.Typings to avoid importing dependencies when exporting type definition files?

**Comment by PandaWood** [comment]
Looks like this is basically the same issue as I reported recently - https://github.com/reinforced/Reinforced.Typings/issues/70

Not exactly the same, but both would be solved by being able to control/removing the generated import statements

**Comment by pavel-b-novikov** [comment]
Duplicates #70
