### ISSUE TITLE
Is also able to generate default field assign for controller layer???

### ISSUE THREAD

**Issue by ganu453** [reinforced/Reinforced.Typings#75]
Suppose I have a controller method which is defined like below 
//Method for which i suppossed to generate TS code
public string getDefaultName(DepartmentNameEnum depart = DepartmentNameEnum.Tech){

}

//But in this case, generate file looks like having
string getDefaultName(depart: DepartmentNameEnum _= Tech)_ ...

But conceptually DepartmentNameEnum _= Tech this is not correct, it is giving a compilation error. Please help me to resolve this

**Comment by pavel-b-novikov** [comment]
Yes, that appears to be bug. I will provide you with workaround soon and it will be fixed in next version

**Comment by ganu453** [comment]
Can I fix it? I know it...

**Comment by pavel-b-novikov** [comment]
Well, pull requests are welcome

**Comment by ganu453** [comment]
Thanks pavel-b-novikov for merging, also currently status is open but can be marked as after release

**Comment by pavel-b-novikov** [comment]
Went into 1.4.96 release
