### ISSUE TITLE
What is alternative of TypeExtensions.GetName method

### ISSUE THREAD

**Issue by ganu453** [reinforced/Reinforced.Typings#77]
It was existed in an earlier release code, but currently, there is no such method which equally fulfills the purpose. Class I am referring is - 
https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings/TypeExtensions.cs

**Comment by pavel-b-novikov** [comment]
After recent refactoring, all information about types was moved into blueprints. So you have to obtain type blueprint that you are interested in by invoking (inside generator) ```var typeBlueprint = Context.Project.Blueprint(typeof(TypeContainingMethodYouNeeded))```. Then you can invoke ```typeBluepring.GetName()``` that will return ```RtSimpleTypeName``` containing name of type you are interested in.
