### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by kfrancis** [reinforced/Reinforced.Typings#8]
> Code generator Reinforced.Typings.Generators.EnumGenerator has thrown an error: Object reference not set to an instance of an object.

I'm trying to work with Enums, using two projects - the main website (which has some TsInterface use in it including TsEnum which works nicely) and a "core" dll that is referenced by the main website, which also contains some models. I've added the "core" library to the settings.xml using RtAdditionalAssembly and it sort of works, but I get this error.

Could you output symbols on the nuget package so I could see line numbers to help diagnose/fix this issue?

**Comment by pavel-b-novikov** [comment]
Let me try to reproduce it by myself.
If I fix this bug then next version will include .pdb file.

**Comment by kfrancis** [comment]
Perfect! So far I'm LOVING this implementation. What I really hated about the others (like TypeLITE) is the use of T4 templates which have never ever worked (outside of any use by Microsoft).

**Comment by pavel-b-novikov** [comment]
Thanks a lot :)
The best that you can do is tell about that to your 10 friends ;)

**Comment by kfrancis** [comment]
I was able to get around this by having the "core" project output the ts file into the web project directly, rather than using RtAdditionalAssembly - must be related to the reflection of that external enum. I used TsReference to get those references automatically put in there.

**Comment by pavel-b-novikov** [comment]
@kfrancis please contact me directly to pavel.b.novikov[at]gmail.com

**Comment by kfrancis** [comment]
@pavel-b-novikov done

**Comment by kfrancis** [comment]
Can't reproduce it now.
