### ISSUE TITLE
Conditionally enable build and compilation dependencies

### ISSUE THREAD

**Issue by santhoshramachandran** [reinforced/Reinforced.Typings#80]
Hi,

My project has multiple csproj and I'm generating a single TS file from only one of those projects. But the decorations of attributes are included in many projects (as shown below)

project1 => Has "Class1" which is exported as TSClass
project2 => Has "Enum2" which is exported as TSEnum
project3 => Reinforced.Typings.Settings.xml is stored here as I want to generate a single TS file from all 3 assemblies

Now I get a warning "RT is disabled in this configuration" in project1 and project2. But those projects will never have settings.xml file. Should we not add the build/compile dependencies only if the settings xml is present to avoid such scenarios? Changes below:

	<PropertyGroup>		
		<TargetsTriggeredByCompilation>
			$(TargetsTriggeredByCompilation);ReinforcedTypingsGenerate;
		</TargetsTriggeredByCompilation>		
		
		<BuildDependsOn>
			ConditionallyDisableTypeScriptCompilation;
			ConditionallyShowDisabledWarning;
			$(BuildDependsOn);
		</BuildDependsOn>
        
        <RtSettingsXml Condition="HasTrailingSlash('$(ProjectDir)')">$(ProjectDir)Reinforced.Typings.settings.xml</RtSettingsXml>
        <RtSettingsXml Condition="!HasTrailingSlash('$(ProjectDir)')">$(ProjectDir)\Reinforced.Typings.settings.xml</RtSettingsXml>
        
        <RtTargetsPath Condition=" '$(MSBuildRuntimeType)' == 'Core'">netstandard1.6</RtTargetsPath>
        <RtTargetsPath Condition=" '$(MSBuildRuntimeType)' != 'Core'">net45</RtTargetsPath>
	</PropertyGroup>

to

	<PropertyGroup>		
        <RtSettingsXml Condition="HasTrailingSlash('$(ProjectDir)')">$(ProjectDir)Reinforced.Typings.settings.xml</RtSettingsXml>
        <RtSettingsXml Condition="!HasTrailingSlash('$(ProjectDir)')">$(ProjectDir)\Reinforced.Typings.settings.xml</RtSettingsXml>
        
        <RtTargetsPath Condition=" '$(MSBuildRuntimeType)' == 'Core'">netstandard1.6</RtTargetsPath>
        <RtTargetsPath Condition=" '$(MSBuildRuntimeType)' != 'Core'">net45</RtTargetsPath>
	</PropertyGroup>
    
	<PropertyGroup Condition="Exists($(RtSettingsXml))" >
		<TargetsTriggeredByCompilation>
			$(TargetsTriggeredByCompilation);ReinforcedTypingsGenerate;
		</TargetsTriggeredByCompilation>		
		
		<BuildDependsOn>
			ConditionallyDisableTypeScriptCompilation;
			ConditionallyShowDisabledWarning;
			$(BuildDependsOn);
		</BuildDependsOn>
	</PropertyGroup>

Please let me know your thoughts on this.

Thanks,
Santhosh

**Comment by santhoshramachandran** [comment]
@pavel-b-novikov Can you please let me know if the above suggestions sounds reasonable to you?

**Comment by pavel-b-novikov** [comment]
Yes. That sounds reasonable and seems like a good feature.

**Comment by santhoshramachandran** [comment]
Thanks. Can you please let me know when you're planning to create a new release? We would want to consume these changes in our project.

**Comment by pavel-b-novikov** [comment]
Oh. Difficult question. I was on kinda vacation. Now I have some health problems :(

**Comment by santhoshramachandran** [comment]
Take care!!

**Comment by santhoshramachandran** [comment]
Any updates on when the next release is happening?

**Comment by pavel-b-novikov** [comment]
Discussed and fixed in #104
