### ISSUE TITLE
Unable to export class with extends from external file using Fluent API

### ISSUE THREAD

**Issue by rmatejka** [reinforced/Reinforced.Typings#82]
I have the following scenario:
1. Have to use FLuent API only
2. Class B that is derived from class A 
3. Class A & B exports go to separate files
4. Class B builder uses AddImport for class A

The issue I'm encountering is that the export Class B does not include "extends A". The only way I seem to be able to get this to work is to add ExportAsClass<A> in the same builder for class B.

Is there some way to define Class A as an import that is not exported to generate the correct definition? If not, are there plans for adding this capability?

Thanks,
Rick

**Comment by pavel-b-novikov** [comment]
I'm sorry, can you please provide more details. It is not clear from your description what is happening

**Comment by rmatejka** [comment]
Sure. I have this class:
 public class B: A
    {
....
}

and this builder:

builder.AddImport("{ A }", "./ModuleA"); 
builder.ExportAsClass<B>().WithAllProperties();

but it generates this TyperScript:

export class B
{
...
}

but I need/expect:
export class B extends A
{
....
}

**Comment by rmatejka** [comment]
I have a kludgy workaround using a custom code generator which prepends an underscore to the parent class name and adds that to the export to avoid the double-include:

builder.AddImport("{ A }", "./ModuleA");
builder.ExportAsClass< A >()
                   .WithCodeGenerator<NullCodeGenerator>()
                ;
builder.ExportAsClass< B >().WithAllProperties();

OUTPUT
export class _A
{
}
export class B extends A
{
}

**Comment by pavel-b-novikov** [comment]
Ah. The problem is that you don't export base class itself. So in order to keep code compilable, RT does not write "extends" (otherwise I'd have to write "extends" for ```IDisposable```, ```object``` and system collections also). 
If you can write code generators - why don't you write code generator for class ```B``` that manually appends "extends A"? It is quite simple - just add ```new SimpleTypeName("A")``` to ```Implementees``` list.
