### ISSUE TITLE
ExportPureTypings generating export for enums

### ISSUE THREAD

**Issue by marco-gallinari** [reinforced/Reinforced.Typings#84]
I'm using version 1.4.95.

If I configure builder to export pure typings d.ts files, everything works fine with classes, but enums definitions are not generated properly.

RT generates this:

```
export enum MyEnum { 
     ...
}

```
instead of:

```
declare enum MyEnum { 
     ...
}
```

**Comment by pavel-b-novikov** [comment]
Fixed in version 1.5. [Test](https://github.com/reinforced/Reinforced.Typings/blob/features-1.5/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.ExportEnumsInDtsWithDeclareKeyword.cs)
