### ISSUE TITLE
Build scripts could be cross-platform (mono) compatible eg Cake

### ISSUE THREAD

**Issue by PandaWood** [reinforced/Reinforced.Typings#88]
The scripts `cleanup.cmd` and `build.cmd` contain windows-specific commands and don't work on Mono
So I was about to see if I could convert them to use [Cake](https://cakebuild.net/) - which seems like the best build tool for generic .NET projects

I have started doing this but I haven't done much Cake before so we'll so how it goes.

**Comment by pavel-b-novikov** [comment]
Moved 1.5 branch to Cake. Considering this task done.
