### ISSUE TITLE
Setting changes are not respected within Visual Studio until restart

### ISSUE THREAD

**Issue by c-s-n** [reinforced/Reinforced.Typings#92]
**Background**
Building a project with Reinforced.Typings included via `RtConfigurationMethod` within Visual Studio 2017.

**Problem**
Changes to the file `Reinforced.Typings.settings.xml` are not respected until a restart of Visual Studio.

**Possible cause**
`Reinforced.Typings.targets` uses the following MSBuild import of the settings XML:
```XML
<Import Project="$(RtSettingsXml)" Condition="Exists($(RtSettingsXml))" />
```
According to https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2017
> [...] Visual Studio reevaluates the conditions on properties and items, but not on imports. Because the import conditional is not reevaluated, the import is skipped. 

**Expected behavior**
Make the settings XML be re-read on every build, also in Visual Studio, not only on command line.

**Comment by pavel-b-novikov** [comment]
Not sure that I could fix that. 
btw, it works in my VS 2017

**Comment by c-s-n** [comment]
Hi @pavel-b-novikov,

when reading the Microsoft docs, it feels to me as if you should just leave out the `Condition="Exists($(RtSettingsXml))"` from the `Import` element.

Imho that is in any case the correct approach, because there should be an error if there is no config file. I assume that the `Import` element will throw an error if not found.
Note that this would make target `ConditionallyShowNoRtXml` obsolete, which currently anyways has a misleading warning message.

**Comment by pavel-b-novikov** [comment]
Fixed in 1.4.96

**Comment by pavel-b-novikov** [comment]
Btw, settings changes may not take effect until you change your source (.cs) file. Add space symbol somewhere and rebuild your project.

**Comment by Martin-Praznovsky** [comment]
Have you been able to solve this issue? I have a project which when opened in VS2017 everything works perfectly fine, but when I open the same project in VS2019 then RT does nothing, looks like it is not being called at all during build.
