### ISSUE TITLE
Nested types are not documented

### ISSUE THREAD

**Issue by c-s-n** [reinforced/Reinforced.Typings#93]
**Background**
Building JSDOC from XMLDOC via `GenerateDocumentation` fluent configuration.

**Problem**
For nested types (classes and enums), that are explicitly exported via fluent configuration, the JSDOC is missing on the generated TypeScript type itself, as well as on its members.

**Expected behavior**
Proper documentation transpiling also for nested types.

**Comment by pavel-b-novikov** [comment]
[Fixed in 1.5](https://github.com/reinforced/Reinforced.Typings/blob/features-1.5/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.DocumentationForNestedTypes.cs)
