### ISSUE TITLE
MSB6006 code 134 error due to StackOverflowException with JObject property

### ISSUE THREAD

**Issue by takerukoushirou** [reinforced/Reinforced.Typings#94]
Builds suddenly failed with the error message `error MSB6006: "" exited with code 134`; looking at the MSBuild debug output the `rtcli` process was terminated due to a `StackOverflowException`.

After eliminating new candidates it turned out that the cause is a `JObject` property on a class.

Simple test class that causes the problem:
```cs
using Newtonsoft.Json.Linq;
using Reinforced.Typings.Attributes;

namespace BuildError {
    [TsInterface(AutoI = false)]
    public class Test
    {
        public JObject Json { get; set; }
    }
}
```

**Comment by pavel-b-novikov** [comment]
It happens because ```JObject``` implements ```IEnumerable``` or ```IDictionary```. Just override its type explicitly using corresponding substitution/type resolver.

**Comment by takerukoushirou** [comment]
@pavel-b-novikov thanks for the quick reply, the property in this case was just missing the annotation for the explicit type "any", been an easy fix once the cause was found.

I reported the error though because it took a while to find the cause as suddenly a tool crashes during build, even though everything seemed to work just fine a few days ago, and you first wonder whether something broke with the build setup itself.
Is it maybe possible to detect types that cannot be processed or watch the progress and in case of an overflow emit an error with a hint on the currently processed type?

**Comment by pavel-b-novikov** [comment]
I will try to do something with that, but not sure.
