### ISSUE TITLE
Input string as not in correct format

### ISSUE THREAD

**Issue by PeterJD** [reinforced/Reinforced.Typings#98]
converting 
https://github.com/anawatmuangjai/Employee-Management-System
Models convert ok
But controllers just return error
Input string as not in correct format
Project 
EMS.WebCore
File
ReinforcedTypings
Any ideas?

How do you debug on build?
Kind regards
Peter

**Comment by pavel-b-novikov** [comment]
See here: https://github.com/reinforced/Reinforced.Typings/issues/5
